import type { Disease } from "./diseases";

// Compact factory to keep this file readable while adding hundreds of entries.
const d = (
  id: string,
  category: Disease["category"],
  severity: Disease["severity"],
  ar: { name: string; shortDesc: string; symptoms: string[]; causes: string[]; treatments: string[]; research?: string; whatToDo?: string },
  en: { name: string; shortDesc: string; symptoms: string[]; causes: string[]; treatments: string[]; research?: string; whatToDo?: string },
): Disease => ({ id, category, severity, ar, en });

export const diseasesExtra: Disease[] = [
  // ========================= COMMON DISEASES =========================
  d("common-cold", "common", "mild",
    { name: "نزلة البرد", shortDesc: "عدوى فيروسية في الجهاز التنفسي العلوي.", symptoms: ["سيلان الأنف", "عطس", "احتقان حلق", "سعال خفيف"], causes: ["فيروسات الأنف (rhinovirus)", "انتقال بالرذاذ"], treatments: ["راحة", "سوائل", "مسكنات", "مضادات احتقان"] },
    { name: "Common Cold", shortDesc: "Viral upper respiratory infection.", symptoms: ["Runny nose", "Sneezing", "Sore throat", "Mild cough"], causes: ["Rhinoviruses", "Droplet transmission"], treatments: ["Rest", "Fluids", "Analgesics", "Decongestants"] }),
  d("influenza", "common", "moderate",
    { name: "الإنفلونزا", shortDesc: "عدوى فيروسية حادة بالجهاز التنفسي.", symptoms: ["حمى مرتفعة", "آلام عضلية", "تعب شديد", "سعال جاف"], causes: ["فيروسات Influenza A/B"], treatments: ["أوسيلتاميفير في 48 ساعة الأولى", "راحة", "سوائل", "تطعيم سنوي"] },
    { name: "Influenza", shortDesc: "Acute viral respiratory infection.", symptoms: ["High fever", "Muscle aches", "Severe fatigue", "Dry cough"], causes: ["Influenza A/B viruses"], treatments: ["Oseltamivir within 48h", "Rest", "Fluids", "Annual vaccine"] }),
  d("covid19", "common", "moderate",
    { name: "كوفيد-19", shortDesc: "عدوى فيروسية بفيروس كورونا المستجد.", symptoms: ["حمى", "سعال", "فقدان حاسة الشم", "ضيق تنفس"], causes: ["SARS-CoV-2"], treatments: ["باكسلوفيد للحالات عالية الخطورة", "أكسجين", "تطعيم"] },
    { name: "COVID-19", shortDesc: "Infection by SARS-CoV-2 virus.", symptoms: ["Fever", "Cough", "Loss of smell", "Shortness of breath"], causes: ["SARS-CoV-2"], treatments: ["Paxlovid in high-risk", "Oxygen support", "Vaccination"] }),
  d("strep-throat", "common", "mild",
    { name: "التهاب الحلق العقدي", shortDesc: "عدوى بكتيرية بالحلق بمكورات سبحية.", symptoms: ["ألم حلق شديد", "حمى", "تورم لوزتين", "نقاط بيضاء"], causes: ["Streptococcus pyogenes"], treatments: ["بنسلين أو أموكسيسيلين 10 أيام", "غرغرة ملحية"] },
    { name: "Strep Throat", shortDesc: "Bacterial throat infection by Group A Strep.", symptoms: ["Severe sore throat", "Fever", "Swollen tonsils", "White patches"], causes: ["Streptococcus pyogenes"], treatments: ["Penicillin or amoxicillin 10 days", "Salt-water gargle"] }),
  d("pneumonia", "common", "severe",
    { name: "الالتهاب الرئوي", shortDesc: "التهاب وعدوى الحويصلات الهوائية بالرئة.", symptoms: ["سعال مع بلغم", "حمى", "ضيق تنفس", "ألم صدري"], causes: ["بكتيريا Streptococcus pneumoniae", "فيروسات", "فطريات"], treatments: ["مضادات حيوية", "أكسجين", "دخول مستشفى للحالات الشديدة"] },
    { name: "Pneumonia", shortDesc: "Inflammation and infection of lung alveoli.", symptoms: ["Productive cough", "Fever", "Shortness of breath", "Chest pain"], causes: ["Streptococcus pneumoniae", "Viruses", "Fungi"], treatments: ["Antibiotics", "Oxygen", "Hospitalization if severe"] }),
  d("bronchitis", "common", "moderate",
    { name: "التهاب الشعب الهوائية", shortDesc: "التهاب الممرات الهوائية الكبيرة.", symptoms: ["سعال مع بلغم", "أزيز", "تعب", "حرارة خفيفة"], causes: ["فيروسات", "بكتيريا", "تدخين"], treatments: ["موسعات شعب", "إقلاع تدخين", "مضادات حيوية عند الحاجة"] },
    { name: "Bronchitis", shortDesc: "Inflammation of large airways.", symptoms: ["Productive cough", "Wheezing", "Fatigue", "Low fever"], causes: ["Viruses", "Bacteria", "Smoking"], treatments: ["Bronchodilators", "Smoking cessation", "Antibiotics if bacterial"] }),
  d("sinusitis", "common", "mild",
    { name: "التهاب الجيوب الأنفية", shortDesc: "التهاب بطانة الجيوب الأنفية.", symptoms: ["ألم وضغط بالوجه", "احتقان أنف", "إفرازات صفراء", "صداع"], causes: ["عدوى فيروسية", "حساسية", "بكتيريا"], treatments: ["غسول أنفي ملحي", "مضادات احتقان", "مضادات حيوية إذا طال"] },
    { name: "Sinusitis", shortDesc: "Inflammation of sinus lining.", symptoms: ["Facial pain/pressure", "Nasal congestion", "Yellow discharge", "Headache"], causes: ["Viral infection", "Allergies", "Bacteria"], treatments: ["Nasal saline rinse", "Decongestants", "Antibiotics if persistent"] }),
  d("tonsillitis", "common", "mild",
    { name: "التهاب اللوزتين", shortDesc: "التهاب وتورم اللوزتين.", symptoms: ["ألم بلع", "تورم اللوزتين", "حمى", "تضخم الغدد الليمفاوية"], causes: ["فيروس", "بكتيريا"], treatments: ["مضاد حيوي إذا بكتيري", "غرغرة", "استئصال متكرر"] },
    { name: "Tonsillitis", shortDesc: "Inflammation of tonsils.", symptoms: ["Pain swallowing", "Swollen tonsils", "Fever", "Lymph node enlargement"], causes: ["Virus", "Bacteria"], treatments: ["Antibiotics if bacterial", "Gargles", "Tonsillectomy if recurrent"] }),
  d("ear-infection", "common", "mild",
    { name: "التهاب الأذن الوسطى", shortDesc: "عدوى خلف طبلة الأذن، شائع في الأطفال.", symptoms: ["ألم أذن", "حمى", "ضعف سمع مؤقت", "بكاء عند الأطفال"], causes: ["بكتيريا", "نزلات برد متكررة"], treatments: ["مسكنات", "أموكسيسيلين", "أنابيب تهوية للحالات المتكررة"] },
    { name: "Otitis Media", shortDesc: "Middle ear infection, common in children.", symptoms: ["Ear pain", "Fever", "Temporary hearing loss", "Crying in kids"], causes: ["Bacteria", "Frequent colds"], treatments: ["Pain relief", "Amoxicillin", "Tympanostomy tubes if recurrent"] }),
  d("uti", "common", "moderate",
    { name: "التهاب المسالك البولية", shortDesc: "عدوى بكتيرية بالمثانة أو الكلى.", symptoms: ["حرقان عند التبول", "كثرة التبول", "بول عكر", "ألم بالحوض"], causes: ["E. coli", "احتباس بول"], treatments: ["مضاد حيوي (نتروفورانتوين، تريميثوبريم)", "شرب سوائل بكثرة"] },
    { name: "Urinary Tract Infection", shortDesc: "Bacterial bladder/kidney infection.", symptoms: ["Burning urination", "Frequent urination", "Cloudy urine", "Pelvic pain"], causes: ["E. coli", "Urinary retention"], treatments: ["Antibiotics (nitrofurantoin, TMP-SMX)", "Increased fluids"] }),
  d("kidney-stones", "common", "severe",
    { name: "حصوات الكلى", shortDesc: "تكون بلورات صلبة بالمسالك البولية.", symptoms: ["ألم خاصرة شديد", "دم بالبول", "غثيان", "ألم عند التبول"], causes: ["جفاف", "نظام غذائي عالي الملح", "وراثة"], treatments: ["شرب ماء كثير", "مسكنات", "تفتيت بالموجات", "تنظير حالب"] },
    { name: "Kidney Stones", shortDesc: "Hard mineral crystals in urinary tract.", symptoms: ["Severe flank pain", "Blood in urine", "Nausea", "Painful urination"], causes: ["Dehydration", "High-salt diet", "Genetics"], treatments: ["Hydration", "Pain relief", "Lithotripsy", "Ureteroscopy"] }),
  d("gerd", "common", "moderate",
    { name: "ارتجاع المريء", shortDesc: "ارتداد حمض المعدة إلى المريء.", symptoms: ["حرقان صدري", "ارتجاع حامضي", "صعوبة بلع", "سعال ليلي"], causes: ["ضعف العضلة العاصرة", "السمنة", "أكل دسم"], treatments: ["مثبطات مضخة البروتون (أوميبرازول)", "تغيير نمط حياة", "رفع الرأس بالنوم"] },
    { name: "GERD", shortDesc: "Stomach acid refluxing into esophagus.", symptoms: ["Heartburn", "Acid regurgitation", "Difficulty swallowing", "Night cough"], causes: ["Weak LES", "Obesity", "Fatty foods"], treatments: ["PPIs (omeprazole)", "Lifestyle changes", "Elevate head of bed"] }),
  d("ibs", "common", "mild",
    { name: "القولون العصبي", shortDesc: "اضطراب وظيفي بالأمعاء.", symptoms: ["ألم بطن", "انتفاخ", "إسهال أو إمساك متناوب", "غازات"], causes: ["محور دماغ-أمعاء", "توتر", "حساسية طعام"], treatments: ["نظام FODMAP منخفض", "ألياف", "بروبيوتيك", "علاج نفسي معرفي"] },
    { name: "Irritable Bowel Syndrome", shortDesc: "Functional bowel disorder.", symptoms: ["Abdominal pain", "Bloating", "Alternating diarrhea/constipation", "Gas"], causes: ["Gut-brain axis", "Stress", "Food sensitivities"], treatments: ["Low-FODMAP diet", "Fiber", "Probiotics", "CBT"] }),
  d("crohns", "common", "severe",
    { name: "مرض كرون", shortDesc: "التهاب أمعاء مزمن في أي جزء من الجهاز الهضمي.", symptoms: ["إسهال مزمن", "ألم بطن", "فقدان وزن", "تعب"], causes: ["مناعي ذاتي", "وراثة"], treatments: ["كورتيكوستيرويد", "مثبطات مناعة", "بيولوجيات (إنفليكسيماب)", "جراحة عند الحاجة"] },
    { name: "Crohn's Disease", shortDesc: "Chronic inflammatory bowel disease.", symptoms: ["Chronic diarrhea", "Abdominal pain", "Weight loss", "Fatigue"], causes: ["Autoimmune", "Genetics"], treatments: ["Corticosteroids", "Immunomodulators", "Biologics (infliximab)", "Surgery if needed"] }),
  d("ulcerative-colitis", "common", "severe",
    { name: "التهاب القولون التقرحي", shortDesc: "التهاب مزمن بالقولون والمستقيم.", symptoms: ["إسهال دموي", "ألم بطن", "إلحاح للتبرز", "فقدان وزن"], causes: ["مناعي ذاتي"], treatments: ["ميسالامين", "كورتيكوستيرويد", "بيولوجيات", "استئصال قولون للحالات المقاومة"] },
    { name: "Ulcerative Colitis", shortDesc: "Chronic inflammation of colon/rectum.", symptoms: ["Bloody diarrhea", "Abdominal pain", "Urgency", "Weight loss"], causes: ["Autoimmune"], treatments: ["Mesalamine", "Corticosteroids", "Biologics", "Colectomy if refractory"] }),
  d("hepatitis-a", "common", "moderate",
    { name: "التهاب الكبد A", shortDesc: "عدوى فيروسية حادة بالكبد عبر الطعام والماء.", symptoms: ["يرقان", "غثيان", "ألم بطن", "تعب"], causes: ["فيروس HAV من ماء/طعام ملوث"], treatments: ["داعم فقط — يشفى ذاتياً", "تطعيم وقائي"] },
    { name: "Hepatitis A", shortDesc: "Acute liver infection via contaminated food/water.", symptoms: ["Jaundice", "Nausea", "Abdominal pain", "Fatigue"], causes: ["HAV virus", "Contaminated food/water"], treatments: ["Supportive only — self-resolves", "Preventive vaccine"] }),
  d("hepatitis-b", "common", "severe",
    { name: "التهاب الكبد B", shortDesc: "عدوى فيروسية مزمنة بالكبد قد تسبب تليف.", symptoms: ["يرقان", "تعب مزمن", "ألم بطن", "بلا أعراض أحياناً"], causes: ["فيروس HBV عبر الدم والاتصال الجنسي"], treatments: ["تينوفوفير", "إنترفيرون", "تطعيم وقائي"] },
    { name: "Hepatitis B", shortDesc: "Chronic liver infection causing cirrhosis.", symptoms: ["Jaundice", "Chronic fatigue", "Abdominal pain", "Often asymptomatic"], causes: ["HBV virus", "Blood/sexual contact"], treatments: ["Tenofovir", "Interferon", "Preventive vaccine"] }),
  d("hepatitis-c", "common", "severe",
    { name: "التهاب الكبد C", shortDesc: "عدوى فيروسية مزمنة بالكبد، قابلة للشفاء بالأدوية الجديدة.", symptoms: ["تعب", "يرقان", "غالباً صامت لسنوات"], causes: ["فيروس HCV عبر الدم"], treatments: ["مضادات فيروسات مباشرة (سوفوسبوفير) — شفاء >95%"] },
    { name: "Hepatitis C", shortDesc: "Chronic viral liver infection — curable with DAAs.", symptoms: ["Fatigue", "Jaundice", "Often silent for years"], causes: ["HCV virus", "Blood transmission"], treatments: ["Direct-acting antivirals (sofosbuvir) — >95% cure"] }),
  d("cirrhosis", "common", "critical",
    { name: "تليف الكبد", shortDesc: "ندبات مزمنة بالكبد تعطل وظيفته.", symptoms: ["يرقان", "تورم بطن (استسقاء)", "نزيف بدوالي مريء", "ارتباك ذهني"], causes: ["كحول", "فيروسات الكبد", "كبد دهني"], treatments: ["إيقاف السبب", "أدوية مدرة", "زراعة كبد"] },
    { name: "Cirrhosis", shortDesc: "Chronic liver scarring impairing function.", symptoms: ["Jaundice", "Ascites", "Variceal bleeding", "Confusion"], causes: ["Alcohol", "Viral hepatitis", "Fatty liver"], treatments: ["Address cause", "Diuretics", "Liver transplant"] }),
  d("fatty-liver", "common", "moderate",
    { name: "الكبد الدهني", shortDesc: "تراكم دهون بالكبد غير الكحولي (NAFLD).", symptoms: ["غالباً بدون أعراض", "تعب", "ألم بطن أيمن"], causes: ["سمنة", "سكري", "كوليسترول مرتفع"], treatments: ["إنقاص وزن", "تمارين", "ضبط السكر"] },
    { name: "Fatty Liver Disease", shortDesc: "Non-alcoholic fat accumulation in liver (NAFLD).", symptoms: ["Often asymptomatic", "Fatigue", "Right upper quadrant pain"], causes: ["Obesity", "Diabetes", "High cholesterol"], treatments: ["Weight loss", "Exercise", "Glycemic control"] }),
  d("gallstones", "common", "moderate",
    { name: "حصوات المرارة", shortDesc: "بلورات كوليسترول/أملاح بالمرارة.", symptoms: ["ألم شديد بالجانب الأيمن", "غثيان بعد الأكل الدسم", "يرقان"], causes: ["كوليسترول مرتفع", "وراثة", "أنوثة فوق الأربعين"], treatments: ["استئصال مرارة بالمنظار", "أدوية تذويب للحالات المختارة"] },
    { name: "Gallstones", shortDesc: "Cholesterol/salt crystals in gallbladder.", symptoms: ["Right-sided pain", "Post-meal nausea", "Jaundice"], causes: ["High cholesterol", "Genetics", "Female 40+"], treatments: ["Laparoscopic cholecystectomy", "Bile acid dissolution in select cases"] }),
  d("appendicitis", "emergency", "severe",
    { name: "التهاب الزائدة الدودية", shortDesc: "التهاب حاد بالزائدة يحتاج جراحة طارئة.", symptoms: ["ألم حول السرة ينتقل لأسفل اليمين", "حمى", "غثيان", "فقدان شهية"], causes: ["انسداد تجويف الزائدة"], treatments: ["استئصال جراحي عاجل", "مضاد حيوي قبل وبعد"], whatToDo: "اذهب للطوارئ فوراً ولا تأكل أو تشرب." },
    { name: "Appendicitis", shortDesc: "Acute appendix inflammation requiring emergency surgery.", symptoms: ["Periumbilical pain → RLQ", "Fever", "Nausea", "Loss of appetite"], causes: ["Luminal obstruction"], treatments: ["Emergency appendectomy", "Pre/post antibiotics"], whatToDo: "Go to ER immediately. Nothing by mouth." }),
  d("hemorrhoids", "common", "mild",
    { name: "البواسير", shortDesc: "أوردة منتفخة بالمستقيم/الشرج.", symptoms: ["نزيف عند التبرز", "حكة", "ألم", "كتلة بالشرج"], causes: ["إمساك مزمن", "حمل", "وقوف طويل"], treatments: ["ألياف وسوائل", "كريمات موضعية", "ربط مطاطي", "جراحة للحالات الشديدة"] },
    { name: "Hemorrhoids", shortDesc: "Swollen rectal/anal veins.", symptoms: ["Rectal bleeding", "Itching", "Pain", "Anal lump"], causes: ["Chronic constipation", "Pregnancy", "Prolonged standing"], treatments: ["Fiber and fluids", "Topical creams", "Rubber band ligation", "Surgery if severe"] }),
  d("constipation", "common", "mild",
    { name: "الإمساك", shortDesc: "صعوبة أو ندرة التبرز.", symptoms: ["تبرز أقل من 3 مرات/أسبوع", "براز صلب", "إجهاد", "إحساس بعدم تفريغ كامل"], causes: ["نقص ألياف", "نقص ماء", "قلة حركة", "أدوية"], treatments: ["ألياف 25-30 جم/يوم", "ماء وفير", "ملينات أسموزية"] },
    { name: "Constipation", shortDesc: "Difficult or infrequent defecation.", symptoms: ["<3 stools/week", "Hard stools", "Straining", "Incomplete evacuation"], causes: ["Low fiber", "Low water", "Inactivity", "Medications"], treatments: ["25-30g fiber/day", "Hydration", "Osmotic laxatives"] }),
  d("food-poisoning", "common", "moderate",
    { name: "التسمم الغذائي", shortDesc: "أعراض هضمية بعد تناول طعام ملوث.", symptoms: ["إسهال", "قيء", "ألم بطن", "حمى"], causes: ["Salmonella", "E. coli", "Norovirus"], treatments: ["تعويض سوائل وأملاح (ORS)", "مضاد حيوي للحالات المحددة"], whatToDo: "اشرب سوائل بكثرة. اذهب للطوارئ إذا كان هناك دم بالبراز أو جفاف شديد." },
    { name: "Food Poisoning", shortDesc: "GI illness from contaminated food.", symptoms: ["Diarrhea", "Vomiting", "Abdominal pain", "Fever"], causes: ["Salmonella", "E. coli", "Norovirus"], treatments: ["Oral rehydration (ORS)", "Antibiotics in select cases"], whatToDo: "Drink fluids. ER if bloody stool or severe dehydration." }),
  d("eczema", "common", "mild",
    { name: "الإكزيما", shortDesc: "التهاب جلدي مزمن مع جفاف وحكة.", symptoms: ["حكة شديدة", "احمرار", "جفاف", "تشقق جلد"], causes: ["وراثة", "حساسية", "خلل حاجز الجلد"], treatments: ["مرطبات", "كورتيزون موضعي", "تجنب المحفزات", "مثبطات JAK جديدة"] },
    { name: "Eczema (Atopic Dermatitis)", shortDesc: "Chronic itchy skin inflammation.", symptoms: ["Severe itching", "Redness", "Dryness", "Skin cracks"], causes: ["Genetics", "Allergies", "Skin barrier dysfunction"], treatments: ["Moisturizers", "Topical steroids", "Trigger avoidance", "New JAK inhibitors"] }),
  d("psoriasis", "common", "moderate",
    { name: "الصدفية", shortDesc: "اضطراب مناعي يسبب طبقات قشرية فضية على الجلد.", symptoms: ["لويحات حمراء", "قشور فضية", "حكة", "ألم مفاصل أحياناً"], causes: ["مناعي ذاتي", "وراثة"], treatments: ["كريمات كورتيزون", "علاج ضوئي", "بيولوجيات (أداليموماب)"] },
    { name: "Psoriasis", shortDesc: "Autoimmune disorder causing silvery skin scales.", symptoms: ["Red plaques", "Silvery scales", "Itching", "Joint pain sometimes"], causes: ["Autoimmune", "Genetics"], treatments: ["Topical steroids", "Phototherapy", "Biologics (adalimumab)"] }),
  d("acne", "common", "mild",
    { name: "حب الشباب", shortDesc: "اضطراب جلدي شائع بالغدد الدهنية.", symptoms: ["رؤوس سوداء", "بثور", "كيسات", "ندبات"], causes: ["هرمونات", "بكتيريا P. acnes", "وراثة"], treatments: ["بنزويل بيروكسيد", "ريتينوئيدات", "أيزوتريتينوين للشديدة"] },
    { name: "Acne", shortDesc: "Common skin disorder of sebaceous glands.", symptoms: ["Blackheads", "Pimples", "Cysts", "Scarring"], causes: ["Hormones", "P. acnes bacteria", "Genetics"], treatments: ["Benzoyl peroxide", "Retinoids", "Isotretinoin for severe"] }),
  d("rosacea", "common", "mild",
    { name: "الوردية", shortDesc: "احمرار مزمن في الوجه مع توسع شعيرات.", symptoms: ["احمرار وجه", "بثور", "شعيرات بارزة", "تهيج عيون"], causes: ["غير معروف", "محفزات حرارية وغذائية"], treatments: ["مترونيدازول موضعي", "ليزر للأوعية", "تجنب المحفزات"] },
    { name: "Rosacea", shortDesc: "Chronic facial redness with telangiectasia.", symptoms: ["Facial flushing", "Pustules", "Visible vessels", "Eye irritation"], causes: ["Unknown", "Heat/food triggers"], treatments: ["Topical metronidazole", "Vascular laser", "Trigger avoidance"] }),
  d("vitiligo", "common", "mild",
    { name: "البهاق", shortDesc: "فقدان صبغة الميلانين بأماكن من الجلد.", symptoms: ["بقع بيضاء بالجلد", "شعر أبيض"], causes: ["مناعي ذاتي"], treatments: ["كورتيزون موضعي", "مثبطات كالسينيورين", "علاج ضوئي بـ UVB", "ريتيفلوماب"] },
    { name: "Vitiligo", shortDesc: "Loss of skin melanin pigment.", symptoms: ["White patches", "White hair"], causes: ["Autoimmune"], treatments: ["Topical steroids", "Calcineurin inhibitors", "UVB phototherapy", "Ruxolitinib cream"] }),
  d("shingles", "common", "moderate",
    { name: "الحزام الناري", shortDesc: "إعادة تنشيط فيروس جدري الماء بالأعصاب.", symptoms: ["طفح مؤلم بشريط واحد", "حرقان", "حمى"], causes: ["فيروس Varicella-zoster"], treatments: ["أسيكلوفير في 72 ساعة الأولى", "مسكنات أعصاب", "تطعيم Shingrix"] },
    { name: "Shingles", shortDesc: "Reactivation of chickenpox virus along nerve.", symptoms: ["Painful dermatomal rash", "Burning", "Fever"], causes: ["Varicella-zoster virus"], treatments: ["Acyclovir within 72h", "Neuropathic pain meds", "Shingrix vaccine"] }),
  d("chickenpox", "common", "mild",
    { name: "جدري الماء", shortDesc: "عدوى فيروسية معدية مع طفح بثري.", symptoms: ["طفح حاك", "بثور سائلة", "حمى", "تعب"], causes: ["Varicella-zoster"], treatments: ["مهدئات حكة", "أسيكلوفير للبالغين", "تطعيم وقائي"] },
    { name: "Chickenpox", shortDesc: "Contagious viral infection with vesicular rash.", symptoms: ["Itchy rash", "Fluid blisters", "Fever", "Fatigue"], causes: ["Varicella-zoster"], treatments: ["Antihistamines", "Acyclovir in adults", "Preventive vaccine"] }),
  d("measles", "common", "severe",
    { name: "الحصبة", shortDesc: "عدوى فيروسية شديدة العدوى.", symptoms: ["حمى عالية", "طفح أحمر", "سعال", "بقع كوبليك بالفم"], causes: ["فيروس الحصبة"], treatments: ["داعم", "فيتامين A", "تطعيم MMR وقائي"] },
    { name: "Measles", shortDesc: "Highly contagious viral infection.", symptoms: ["High fever", "Red rash", "Cough", "Koplik spots"], causes: ["Measles virus"], treatments: ["Supportive", "Vitamin A", "MMR vaccine"] }),
  d("mumps", "common", "moderate",
    { name: "النكاف", shortDesc: "عدوى فيروسية بالغدد اللعابية.", symptoms: ["تورم خد مؤلم", "حمى", "صداع", "ألم بلع"], causes: ["فيروس النكاف"], treatments: ["داعم", "تطعيم MMR وقائي"] },
    { name: "Mumps", shortDesc: "Viral infection of salivary glands.", symptoms: ["Painful cheek swelling", "Fever", "Headache", "Difficulty swallowing"], causes: ["Mumps virus"], treatments: ["Supportive", "MMR vaccine"] }),
  d("rubella", "common", "mild",
    { name: "الحصبة الألمانية", shortDesc: "عدوى فيروسية خفيفة لكن خطرة بالحمل.", symptoms: ["طفح وردي خفيف", "حمى", "تورم غدد ليمفاوية"], causes: ["فيروس الروبيلا"], treatments: ["داعم", "تطعيم MMR قبل الحمل"] },
    { name: "Rubella", shortDesc: "Mild viral infection — dangerous in pregnancy.", symptoms: ["Pink rash", "Fever", "Lymphadenopathy"], causes: ["Rubella virus"], treatments: ["Supportive", "MMR vaccine pre-pregnancy"] }),
  d("conjunctivitis", "common", "mild",
    { name: "التهاب الملتحمة", shortDesc: "التهاب بياض العين.", symptoms: ["احمرار عين", "إفرازات", "حكة", "تدميع"], causes: ["فيروس", "بكتيريا", "حساسية"], treatments: ["كمادات", "قطرات مضاد حيوي", "مضادات هيستامين"] },
    { name: "Conjunctivitis (Pink Eye)", shortDesc: "Inflammation of eye conjunctiva.", symptoms: ["Red eye", "Discharge", "Itching", "Tearing"], causes: ["Virus", "Bacteria", "Allergy"], treatments: ["Compresses", "Antibiotic drops", "Antihistamines"] }),
  d("glaucoma", "common", "severe",
    { name: "الزرق (الجلوكوما)", shortDesc: "ارتفاع ضغط العين يدمر العصب البصري.", symptoms: ["فقد بصر طرفي تدريجي", "هالات حول الأضواء", "ألم عين بالنوبة الحادة"], causes: ["وراثة", "تقدم بالعمر"], treatments: ["قطرات (تيمولول، لاتانوبروست)", "ليزر", "جراحة"] },
    { name: "Glaucoma", shortDesc: "Elevated eye pressure damaging optic nerve.", symptoms: ["Gradual peripheral vision loss", "Halos around lights", "Eye pain in acute"], causes: ["Genetics", "Aging"], treatments: ["Drops (timolol, latanoprost)", "Laser", "Surgery"] }),
  d("cataracts", "common", "moderate",
    { name: "إعتام عدسة العين (الكتاراكت)", shortDesc: "تعكر عدسة العين مع تقدم العمر.", symptoms: ["رؤية ضبابية", "وهج بالليل", "ألوان باهتة", "احتياج إضاءة قوية"], causes: ["شيخوخة", "سكري", "تعرض شمس"], treatments: ["جراحة استبدال عدسة"] },
    { name: "Cataracts", shortDesc: "Clouding of eye lens with aging.", symptoms: ["Blurry vision", "Night glare", "Faded colors", "Need bright light"], causes: ["Aging", "Diabetes", "Sun exposure"], treatments: ["Lens replacement surgery"] }),
  d("macular-degeneration", "common", "severe",
    { name: "الضمور البقعي", shortDesc: "تدهور البقعة بالشبكية مع التقدم بالعمر.", symptoms: ["فقد رؤية مركزية", "تشوه خطوط مستقيمة", "صعوبة قراءة"], causes: ["شيخوخة", "تدخين", "وراثة"], treatments: ["مكملات AREDS2", "حقن مضادة لـ VEGF (رانيبيزوماب)"] },
    { name: "Macular Degeneration", shortDesc: "Age-related retinal macula deterioration.", symptoms: ["Central vision loss", "Distorted lines", "Reading difficulty"], causes: ["Aging", "Smoking", "Genetics"], treatments: ["AREDS2 supplements", "Anti-VEGF injections (ranibizumab)"] }),
  d("hypothyroidism", "common", "moderate",
    { name: "قصور الغدة الدرقية", shortDesc: "إنتاج غير كافٍ من هرمون الثيروكسين.", symptoms: ["تعب", "زيادة وزن", "برودة", "إمساك", "اكتئاب"], causes: ["مناعي (هاشيموتو)", "نقص يود", "بعد جراحة درقية"], treatments: ["ليفوثيروكسين مدى الحياة"] },
    { name: "Hypothyroidism", shortDesc: "Insufficient thyroxine production.", symptoms: ["Fatigue", "Weight gain", "Cold intolerance", "Constipation", "Depression"], causes: ["Hashimoto's", "Iodine deficiency", "Post-thyroidectomy"], treatments: ["Lifelong levothyroxine"] }),
  d("hyperthyroidism", "common", "moderate",
    { name: "فرط نشاط الغدة الدرقية", shortDesc: "إنتاج زائد من هرمون الدرقية.", symptoms: ["خفقان", "نقص وزن", "عصبية", "رعشة", "إسهال"], causes: ["جريفز", "عقد سامة"], treatments: ["ميثيمازول", "يود مشع", "جراحة"] },
    { name: "Hyperthyroidism", shortDesc: "Excess thyroid hormone production.", symptoms: ["Palpitations", "Weight loss", "Anxiety", "Tremor", "Diarrhea"], causes: ["Graves' disease", "Toxic nodules"], treatments: ["Methimazole", "Radioactive iodine", "Surgery"] }),
  d("anemia-b12", "common", "moderate",
    { name: "أنيميا نقص فيتامين B12", shortDesc: "نقص B12 يسبب أنيميا ضخمة الأرومات.", symptoms: ["تعب", "خدر أطراف", "صعوبة توازن", "شحوب"], causes: ["نقص غذائي", "فقر دم خبيث", "أمراض هضم"], treatments: ["حقن B12", "أقراص جرعة عالية"] },
    { name: "Vitamin B12 Deficiency Anemia", shortDesc: "B12 deficiency causing megaloblastic anemia.", symptoms: ["Fatigue", "Limb numbness", "Balance issues", "Pallor"], causes: ["Dietary lack", "Pernicious anemia", "Malabsorption"], treatments: ["B12 injections", "High-dose oral B12"] }),
  d("osteoporosis", "common", "moderate",
    { name: "هشاشة العظام", shortDesc: "نقص كثافة العظام يزيد خطر الكسور.", symptoms: ["كسور بسهولة", "نقص طول", "انحناء ظهر"], causes: ["انقطاع طمث", "نقص كالسيوم", "وراثة"], treatments: ["كالسيوم وفيتامين D", "بيسفوسفونات (أليندرونات)", "ديوكسوماب"] },
    { name: "Osteoporosis", shortDesc: "Reduced bone density increasing fracture risk.", symptoms: ["Easy fractures", "Height loss", "Kyphosis"], causes: ["Menopause", "Calcium deficiency", "Genetics"], treatments: ["Calcium + Vitamin D", "Bisphosphonates", "Denosumab"] }),
  d("osteoarthritis", "common", "moderate",
    { name: "خشونة المفاصل", shortDesc: "تآكل غضروف المفصل مع العمر.", symptoms: ["ألم مفصل بالحركة", "تيبس صباحي قصير", "طقطقة", "تورم"], causes: ["شيخوخة", "إصابات", "سمنة"], treatments: ["إنقاص وزن", "علاج طبيعي", "مسكنات", "حقن هيالورونيك", "استبدال مفصل"] },
    { name: "Osteoarthritis", shortDesc: "Age-related joint cartilage wear.", symptoms: ["Movement pain", "Brief morning stiffness", "Crepitus", "Swelling"], causes: ["Aging", "Injuries", "Obesity"], treatments: ["Weight loss", "PT", "Analgesics", "Hyaluronic injections", "Joint replacement"] }),
  d("rheumatoid-arthritis", "common", "severe",
    { name: "الروماتويد (التهاب المفاصل الروماتويدي)", shortDesc: "مرض مناعي يهاجم المفاصل بشكل متماثل.", symptoms: ["تيبس صباحي طويل", "تورم متماثل", "تعب", "ألم"], causes: ["مناعي ذاتي"], treatments: ["ميثوتركسات", "بيولوجيات (إنفليكسيماب)", "كورتيزون"] },
    { name: "Rheumatoid Arthritis", shortDesc: "Autoimmune symmetric joint disease.", symptoms: ["Long morning stiffness", "Symmetric swelling", "Fatigue", "Pain"], causes: ["Autoimmune"], treatments: ["Methotrexate", "Biologics (infliximab)", "Steroids"] }),
  d("gout", "common", "moderate",
    { name: "النقرس", shortDesc: "ترسب بلورات يورات بالمفاصل.", symptoms: ["ألم شديد مفاجئ بإصبع القدم الكبير", "احمرار", "حرارة"], causes: ["ارتفاع حمض اليوريك", "أكل لحوم حمراء", "كحول"], treatments: ["كولشيسين أو NSAID للنوبة", "ألوبيورينول للوقاية"] },
    { name: "Gout", shortDesc: "Uric acid crystal deposition in joints.", symptoms: ["Sudden severe big toe pain", "Redness", "Warmth"], causes: ["High uric acid", "Red meat", "Alcohol"], treatments: ["Colchicine/NSAID for attack", "Allopurinol prevention"] }),
  d("lupus", "common", "severe",
    { name: "الذئبة الحمامية", shortDesc: "مرض مناعي يصيب الجلد والمفاصل والأعضاء.", symptoms: ["طفح فراشة بالوجه", "ألم مفاصل", "تعب", "حمى", "حساسية شمس"], causes: ["مناعي ذاتي", "وراثة وهرمونات"], treatments: ["هيدروكسي كلوروكوين", "كورتيزون", "بيلموماب"] },
    { name: "Lupus (SLE)", shortDesc: "Autoimmune disease affecting skin/joints/organs.", symptoms: ["Butterfly facial rash", "Joint pain", "Fatigue", "Fever", "Photosensitivity"], causes: ["Autoimmune", "Genetics + hormones"], treatments: ["Hydroxychloroquine", "Steroids", "Belimumab"] }),
  d("ms", "common", "severe",
    { name: "التصلب اللويحي", shortDesc: "مرض مناعي يدمر غلاف ميالين الأعصاب.", symptoms: ["ضعف عضلي", "تنميل", "اضطرابات بصر", "مشاكل توازن", "تعب شديد"], causes: ["مناعي ذاتي"], treatments: ["إنترفيرون بيتا", "أوكريليزوماب", "علاج طبيعي"] },
    { name: "Multiple Sclerosis", shortDesc: "Autoimmune destruction of nerve myelin.", symptoms: ["Muscle weakness", "Numbness", "Vision problems", "Balance issues", "Severe fatigue"], causes: ["Autoimmune"], treatments: ["Interferon beta", "Ocrelizumab", "Physical therapy"] }),
  d("parkinsons", "common", "severe",
    { name: "مرض باركنسون", shortDesc: "اضطراب عصبي تنكسي يؤثر على الحركة.", symptoms: ["رعشة وقت الراحة", "تيبس", "بطء حركة", "اختلال توازن"], causes: ["موت خلايا منتجة للدوبامين", "وراثة"], treatments: ["ليفودوبا", "محفزات دوبامين", "تحفيز عميق للدماغ DBS"] },
    { name: "Parkinson's Disease", shortDesc: "Neurodegenerative movement disorder.", symptoms: ["Resting tremor", "Rigidity", "Bradykinesia", "Postural instability"], causes: ["Dopamine neuron loss", "Genetics"], treatments: ["Levodopa", "Dopamine agonists", "Deep brain stimulation"] }),
  d("alzheimers", "common", "critical",
    { name: "مرض الزهايمر", shortDesc: "أكثر أسباب الخرف شيوعاً.", symptoms: ["نسيان حديث", "تدهور لغة", "تشوش", "تغير شخصية"], causes: ["لويحات بيتا أميلويد", "وراثة (APOE4)"], treatments: ["دونيبيزيل", "ميمانتين", "ليكانيماب الجديد", "دعم نفسي للمريض والأسرة"] },
    { name: "Alzheimer's Disease", shortDesc: "Most common cause of dementia.", symptoms: ["Recent memory loss", "Language decline", "Confusion", "Personality change"], causes: ["Beta-amyloid plaques", "APOE4 genetics"], treatments: ["Donepezil", "Memantine", "Lecanemab (new)", "Caregiver support"] }),
  d("dementia-vascular", "common", "severe",
    { name: "الخرف الوعائي", shortDesc: "خرف بسبب تكرر السكتات الصغيرة.", symptoms: ["تدهور تدريجي ومتدرج", "بطء تفكير", "صعوبة تخطيط", "مشاكل مزاج"], causes: ["تصلب شرايين", "ضغط مرتفع", "سكري"], treatments: ["ضبط عوامل الخطر", "أسبرين", "ستاتين"] },
    { name: "Vascular Dementia", shortDesc: "Dementia from recurrent mini-strokes.", symptoms: ["Stepwise decline", "Slow thinking", "Planning difficulty", "Mood changes"], causes: ["Atherosclerosis", "Hypertension", "Diabetes"], treatments: ["Risk factor control", "Aspirin", "Statins"] }),
  d("copd", "common", "severe",
    { name: "الانسداد الرئوي المزمن", shortDesc: "انسداد تدفق الهواء غير قابل للعكس.", symptoms: ["ضيق تنفس", "سعال مزمن", "بلغم", "صفير"], causes: ["تدخين", "تلوث هواء"], treatments: ["إقلاع تدخين", "موسعات شعب", "أكسجين منزلي", "تأهيل رئوي"] },
    { name: "COPD", shortDesc: "Irreversible airflow obstruction.", symptoms: ["Dyspnea", "Chronic cough", "Sputum", "Wheezing"], causes: ["Smoking", "Air pollution"], treatments: ["Smoking cessation", "Bronchodilators", "Home oxygen", "Pulmonary rehab"] }),
  d("tb", "common", "severe",
    { name: "السل (الدرن)", shortDesc: "عدوى بكتيرية مزمنة، غالباً بالرئة.", symptoms: ["سعال >3 أسابيع مع دم", "حمى ليلية", "تعرق ليلي", "نقص وزن"], causes: ["Mycobacterium tuberculosis"], treatments: ["RIPE 6 أشهر (ريفامبيسين، إيزونيازيد، بيرازيناميد، إيثامبوتول)"] },
    { name: "Tuberculosis (TB)", shortDesc: "Chronic bacterial infection, usually lungs.", symptoms: ["Cough >3 weeks with blood", "Night fever", "Night sweats", "Weight loss"], causes: ["Mycobacterium tuberculosis"], treatments: ["6-month RIPE regimen (Rifampicin, Isoniazid, Pyrazinamide, Ethambutol)"] })
];
