export interface EmergencyContact {
  country: string;
  countryAr: string;
  flag: string;
  emergency: string;
  ambulance?: string;
  police?: string;
  fire?: string;
  poison?: string;
  mentalCrisis?: string;
  region: "arab" | "africa" | "asia" | "europe" | "americas" | "oceania";
}

// Official public emergency numbers — sourced from government/embassy publications and Wikipedia's
// "List of emergency telephone numbers". Always verify locally before travel.
export const emergencyNumbers: EmergencyContact[] = [
  // ===== ARAB COUNTRIES =====
  { country: "Egypt", countryAr: "مصر", flag: "🇪🇬", region: "arab", emergency: "123", ambulance: "123", police: "122", fire: "180", mentalCrisis: "08008880700" },
  { country: "Saudi Arabia", countryAr: "السعودية", flag: "🇸🇦", region: "arab", emergency: "911", ambulance: "997", police: "999", fire: "998", mentalCrisis: "920033360" },
  { country: "United Arab Emirates", countryAr: "الإمارات", flag: "🇦🇪", region: "arab", emergency: "999", ambulance: "998", police: "999", fire: "997", mentalCrisis: "800-HOPE" },
  { country: "Kuwait", countryAr: "الكويت", flag: "🇰🇼", region: "arab", emergency: "112", ambulance: "112", police: "112" },
  { country: "Qatar", countryAr: "قطر", flag: "🇶🇦", region: "arab", emergency: "999", ambulance: "999" },
  { country: "Bahrain", countryAr: "البحرين", flag: "🇧🇭", region: "arab", emergency: "999" },
  { country: "Oman", countryAr: "عُمان", flag: "🇴🇲", region: "arab", emergency: "9999" },
  { country: "Jordan", countryAr: "الأردن", flag: "🇯🇴", region: "arab", emergency: "911", ambulance: "911", police: "911" },
  { country: "Lebanon", countryAr: "لبنان", flag: "🇱🇧", region: "arab", emergency: "112", ambulance: "140", fire: "175" },
  { country: "Iraq", countryAr: "العراق", flag: "🇮🇶", region: "arab", emergency: "104", ambulance: "122", police: "104" },
  { country: "Syria", countryAr: "سوريا", flag: "🇸🇾", region: "arab", emergency: "112", ambulance: "110" },
  { country: "Palestine", countryAr: "فلسطين", flag: "🇵🇸", region: "arab", emergency: "101", ambulance: "101" },
  { country: "Yemen", countryAr: "اليمن", flag: "🇾🇪", region: "arab", emergency: "191", ambulance: "191" },
  { country: "Morocco", countryAr: "المغرب", flag: "🇲🇦", region: "arab", emergency: "15", ambulance: "15", police: "19" },
  { country: "Algeria", countryAr: "الجزائر", flag: "🇩🇿", region: "arab", emergency: "14", ambulance: "14", police: "17" },
  { country: "Tunisia", countryAr: "تونس", flag: "🇹🇳", region: "arab", emergency: "190", ambulance: "190", police: "197" },
  { country: "Libya", countryAr: "ليبيا", flag: "🇱🇾", region: "arab", emergency: "1515", ambulance: "1515" },
  { country: "Sudan", countryAr: "السودان", flag: "🇸🇩", region: "arab", emergency: "999" },
  { country: "Mauritania", countryAr: "موريتانيا", flag: "🇲🇷", region: "arab", emergency: "117", ambulance: "118" },
  { country: "Somalia", countryAr: "الصومال", flag: "🇸🇴", region: "arab", emergency: "888" },
  { country: "Djibouti", countryAr: "جيبوتي", flag: "🇩🇯", region: "arab", emergency: "17", ambulance: "19" },
  { country: "Comoros", countryAr: "جزر القمر", flag: "🇰🇲", region: "arab", emergency: "17" },

  // ===== AFRICA =====
  { country: "South Africa", countryAr: "جنوب أفريقيا", flag: "🇿🇦", region: "africa", emergency: "112", ambulance: "10177", police: "10111" },
  { country: "Nigeria", countryAr: "نيجيريا", flag: "🇳🇬", region: "africa", emergency: "112", police: "199" },
  { country: "Kenya", countryAr: "كينيا", flag: "🇰🇪", region: "africa", emergency: "999", ambulance: "112" },
  { country: "Ethiopia", countryAr: "إثيوبيا", flag: "🇪🇹", region: "africa", emergency: "991", ambulance: "907", police: "991" },
  { country: "Ghana", countryAr: "غانا", flag: "🇬🇭", region: "africa", emergency: "112", ambulance: "193", police: "191", fire: "192" },
  { country: "Tanzania", countryAr: "تنزانيا", flag: "🇹🇿", region: "africa", emergency: "112", police: "111" },
  { country: "Uganda", countryAr: "أوغندا", flag: "🇺🇬", region: "africa", emergency: "999", police: "112" },
  { country: "Senegal", countryAr: "السنغال", flag: "🇸🇳", region: "africa", emergency: "17", ambulance: "1515" },
  { country: "Côte d'Ivoire", countryAr: "ساحل العاج", flag: "🇨🇮", region: "africa", emergency: "111", ambulance: "185", police: "170" },
  { country: "Cameroon", countryAr: "الكاميرون", flag: "🇨🇲", region: "africa", emergency: "112", ambulance: "119", police: "117" },
  { country: "Zimbabwe", countryAr: "زيمبابوي", flag: "🇿🇼", region: "africa", emergency: "999", ambulance: "994", police: "995" },
  { country: "Zambia", countryAr: "زامبيا", flag: "🇿🇲", region: "africa", emergency: "999", ambulance: "991", police: "991" },
  { country: "Botswana", countryAr: "بوتسوانا", flag: "🇧🇼", region: "africa", emergency: "999", ambulance: "997", police: "999" },
  { country: "Namibia", countryAr: "ناميبيا", flag: "🇳🇦", region: "africa", emergency: "112", ambulance: "211111" },
  { country: "Mozambique", countryAr: "موزمبيق", flag: "🇲🇿", region: "africa", emergency: "119", police: "119" },
  { country: "Angola", countryAr: "أنغولا", flag: "🇦🇴", region: "africa", emergency: "113", ambulance: "116" },
  { country: "DR Congo", countryAr: "الكونغو الديمقراطية", flag: "🇨🇩", region: "africa", emergency: "112" },
  { country: "Rwanda", countryAr: "رواندا", flag: "🇷🇼", region: "africa", emergency: "112", ambulance: "912", police: "112" },
  { country: "Burundi", countryAr: "بوروندي", flag: "🇧🇮", region: "africa", emergency: "117" },
  { country: "Madagascar", countryAr: "مدغشقر", flag: "🇲🇬", region: "africa", emergency: "117", ambulance: "124" },
  { country: "Mauritius", countryAr: "موريشيوس", flag: "🇲🇺", region: "africa", emergency: "999", ambulance: "114", police: "999" },
  { country: "Seychelles", countryAr: "سيشل", flag: "🇸🇨", region: "africa", emergency: "999" },
  { country: "Mali", countryAr: "مالي", flag: "🇲🇱", region: "africa", emergency: "15", police: "17" },
  { country: "Niger", countryAr: "النيجر", flag: "🇳🇪", region: "africa", emergency: "15", police: "17" },
  { country: "Burkina Faso", countryAr: "بوركينا فاسو", flag: "🇧🇫", region: "africa", emergency: "112", ambulance: "112" },
  { country: "Chad", countryAr: "تشاد", flag: "🇹🇩", region: "africa", emergency: "17", police: "17" },
  { country: "Central African Republic", countryAr: "إفريقيا الوسطى", flag: "🇨🇫", region: "africa", emergency: "117" },
  { country: "Gabon", countryAr: "الغابون", flag: "🇬🇦", region: "africa", emergency: "1300" },
  { country: "Republic of the Congo", countryAr: "الكونغو", flag: "🇨🇬", region: "africa", emergency: "112" },
  { country: "Equatorial Guinea", countryAr: "غينيا الاستوائية", flag: "🇬🇶", region: "africa", emergency: "112" },
  { country: "Liberia", countryAr: "ليبيريا", flag: "🇱🇷", region: "africa", emergency: "911" },
  { country: "Sierra Leone", countryAr: "سيراليون", flag: "🇸🇱", region: "africa", emergency: "999" },
  { country: "Guinea", countryAr: "غينيا", flag: "🇬🇳", region: "africa", emergency: "117" },
  { country: "Guinea-Bissau", countryAr: "غينيا بيساو", flag: "🇬🇼", region: "africa", emergency: "112" },
  { country: "Gambia", countryAr: "غامبيا", flag: "🇬🇲", region: "africa", emergency: "117" },
  { country: "Cape Verde", countryAr: "الرأس الأخضر", flag: "🇨🇻", region: "africa", emergency: "132", ambulance: "130" },
  { country: "Togo", countryAr: "توغو", flag: "🇹🇬", region: "africa", emergency: "117", ambulance: "118" },
  { country: "Benin", countryAr: "بنين", flag: "🇧🇯", region: "africa", emergency: "117" },
  { country: "Malawi", countryAr: "مالاوي", flag: "🇲🇼", region: "africa", emergency: "997", ambulance: "998" },
  { country: "Lesotho", countryAr: "ليسوتو", flag: "🇱🇸", region: "africa", emergency: "112" },
  { country: "Eswatini", countryAr: "إسواتيني", flag: "🇸🇿", region: "africa", emergency: "999", ambulance: "977" },
  { country: "Eritrea", countryAr: "إريتريا", flag: "🇪🇷", region: "africa", emergency: "127" },
  { country: "South Sudan", countryAr: "جنوب السودان", flag: "🇸🇸", region: "africa", emergency: "777" },
  { country: "São Tomé and Príncipe", countryAr: "ساو تومي", flag: "🇸🇹", region: "africa", emergency: "112" },

  // ===== EUROPE (EU + Others) =====
  { country: "United Kingdom", countryAr: "بريطانيا", flag: "🇬🇧", region: "europe", emergency: "999", ambulance: "999", mentalCrisis: "116123" },
  { country: "Ireland", countryAr: "أيرلندا", flag: "🇮🇪", region: "europe", emergency: "112", mentalCrisis: "116123" },
  { country: "France", countryAr: "فرنسا", flag: "🇫🇷", region: "europe", emergency: "112", ambulance: "15", police: "17", fire: "18" },
  { country: "Germany", countryAr: "ألمانيا", flag: "🇩🇪", region: "europe", emergency: "112", police: "110" },
  { country: "Italy", countryAr: "إيطاليا", flag: "🇮🇹", region: "europe", emergency: "112", ambulance: "118" },
  { country: "Spain", countryAr: "إسبانيا", flag: "🇪🇸", region: "europe", emergency: "112" },
  { country: "Portugal", countryAr: "البرتغال", flag: "🇵🇹", region: "europe", emergency: "112" },
  { country: "Netherlands", countryAr: "هولندا", flag: "🇳🇱", region: "europe", emergency: "112" },
  { country: "Belgium", countryAr: "بلجيكا", flag: "🇧🇪", region: "europe", emergency: "112" },
  { country: "Luxembourg", countryAr: "لوكسمبورغ", flag: "🇱🇺", region: "europe", emergency: "112" },
  { country: "Switzerland", countryAr: "سويسرا", flag: "🇨🇭", region: "europe", emergency: "112", ambulance: "144", police: "117", fire: "118" },
  { country: "Austria", countryAr: "النمسا", flag: "🇦🇹", region: "europe", emergency: "112", ambulance: "144", police: "133", fire: "122" },
  { country: "Denmark", countryAr: "الدنمارك", flag: "🇩🇰", region: "europe", emergency: "112" },
  { country: "Sweden", countryAr: "السويد", flag: "🇸🇪", region: "europe", emergency: "112" },
  { country: "Norway", countryAr: "النرويج", flag: "🇳🇴", region: "europe", emergency: "112", ambulance: "113", police: "112", fire: "110" },
  { country: "Finland", countryAr: "فنلندا", flag: "🇫🇮", region: "europe", emergency: "112" },
  { country: "Iceland", countryAr: "آيسلندا", flag: "🇮🇸", region: "europe", emergency: "112" },
  { country: "Poland", countryAr: "بولندا", flag: "🇵🇱", region: "europe", emergency: "112", ambulance: "999", police: "997", fire: "998" },
  { country: "Czech Republic", countryAr: "التشيك", flag: "🇨🇿", region: "europe", emergency: "112", ambulance: "155", police: "158", fire: "150" },
  { country: "Slovakia", countryAr: "سلوفاكيا", flag: "🇸🇰", region: "europe", emergency: "112" },
  { country: "Hungary", countryAr: "المجر", flag: "🇭🇺", region: "europe", emergency: "112", ambulance: "104", police: "107", fire: "105" },
  { country: "Romania", countryAr: "رومانيا", flag: "🇷🇴", region: "europe", emergency: "112" },
  { country: "Bulgaria", countryAr: "بلغاريا", flag: "🇧🇬", region: "europe", emergency: "112" },
  { country: "Greece", countryAr: "اليونان", flag: "🇬🇷", region: "europe", emergency: "112", ambulance: "166", police: "100", fire: "199" },
  { country: "Croatia", countryAr: "كرواتيا", flag: "🇭🇷", region: "europe", emergency: "112" },
  { country: "Slovenia", countryAr: "سلوفينيا", flag: "🇸🇮", region: "europe", emergency: "112" },
  { country: "Serbia", countryAr: "صربيا", flag: "🇷🇸", region: "europe", emergency: "112", ambulance: "194", police: "192", fire: "193" },
  { country: "Bosnia and Herzegovina", countryAr: "البوسنة والهرسك", flag: "🇧🇦", region: "europe", emergency: "112", ambulance: "124", police: "122", fire: "123" },
  { country: "Montenegro", countryAr: "الجبل الأسود", flag: "🇲🇪", region: "europe", emergency: "112" },
  { country: "North Macedonia", countryAr: "مقدونيا الشمالية", flag: "🇲🇰", region: "europe", emergency: "112" },
  { country: "Albania", countryAr: "ألبانيا", flag: "🇦🇱", region: "europe", emergency: "112", ambulance: "127", police: "129", fire: "128" },
  { country: "Kosovo", countryAr: "كوسوفو", flag: "🇽🇰", region: "europe", emergency: "112" },
  { country: "Estonia", countryAr: "إستونيا", flag: "🇪🇪", region: "europe", emergency: "112" },
  { country: "Latvia", countryAr: "لاتفيا", flag: "🇱🇻", region: "europe", emergency: "112" },
  { country: "Lithuania", countryAr: "ليتوانيا", flag: "🇱🇹", region: "europe", emergency: "112" },
  { country: "Malta", countryAr: "مالطا", flag: "🇲🇹", region: "europe", emergency: "112" },
  { country: "Cyprus", countryAr: "قبرص", flag: "🇨🇾", region: "europe", emergency: "112" },
  { country: "Russia", countryAr: "روسيا", flag: "🇷🇺", region: "europe", emergency: "112", ambulance: "103", police: "102", fire: "101" },
  { country: "Ukraine", countryAr: "أوكرانيا", flag: "🇺🇦", region: "europe", emergency: "112", ambulance: "103", police: "102", fire: "101" },
  { country: "Belarus", countryAr: "بيلاروسيا", flag: "🇧🇾", region: "europe", emergency: "112", ambulance: "103", police: "102", fire: "101" },
  { country: "Moldova", countryAr: "مولدوفا", flag: "🇲🇩", region: "europe", emergency: "112" },
  { country: "Georgia", countryAr: "جورجيا", flag: "🇬🇪", region: "europe", emergency: "112" },
  { country: "Armenia", countryAr: "أرمينيا", flag: "🇦🇲", region: "europe", emergency: "911", ambulance: "103", police: "102", fire: "101" },
  { country: "Azerbaijan", countryAr: "أذربيجان", flag: "🇦🇿", region: "europe", emergency: "112", ambulance: "103", police: "102", fire: "101" },
  { country: "Turkey", countryAr: "تركيا", flag: "🇹🇷", region: "europe", emergency: "112" },
  { country: "Andorra", countryAr: "أندورا", flag: "🇦🇩", region: "europe", emergency: "112" },
  { country: "Monaco", countryAr: "موناكو", flag: "🇲🇨", region: "europe", emergency: "112", ambulance: "15", police: "17", fire: "18" },
  { country: "San Marino", countryAr: "سان مارينو", flag: "🇸🇲", region: "europe", emergency: "112" },
  { country: "Vatican City", countryAr: "الفاتيكان", flag: "🇻🇦", region: "europe", emergency: "112" },
  { country: "Liechtenstein", countryAr: "ليختنشتاين", flag: "🇱🇮", region: "europe", emergency: "112", ambulance: "144", police: "117", fire: "118" },

  // ===== ASIA =====
  { country: "Iran", countryAr: "إيران", flag: "🇮🇷", region: "asia", emergency: "112", ambulance: "115", police: "110", fire: "125" },
  { country: "Israel", countryAr: "إسرائيل", flag: "🇮🇱", region: "asia", emergency: "112", ambulance: "101", police: "100", fire: "102" },
  { country: "Afghanistan", countryAr: "أفغانستان", flag: "🇦🇫", region: "asia", emergency: "119", ambulance: "102", police: "119" },
  { country: "Pakistan", countryAr: "باكستان", flag: "🇵🇰", region: "asia", emergency: "115", ambulance: "115", police: "15", fire: "16" },
  { country: "India", countryAr: "الهند", flag: "🇮🇳", region: "asia", emergency: "112", ambulance: "108", police: "100", fire: "101" },
  { country: "Bangladesh", countryAr: "بنغلاديش", flag: "🇧🇩", region: "asia", emergency: "999" },
  { country: "Sri Lanka", countryAr: "سريلانكا", flag: "🇱🇰", region: "asia", emergency: "119", ambulance: "110", police: "119" },
  { country: "Nepal", countryAr: "نيبال", flag: "🇳🇵", region: "asia", emergency: "100", ambulance: "102", police: "100", fire: "101" },
  { country: "Bhutan", countryAr: "بوتان", flag: "🇧🇹", region: "asia", emergency: "112", ambulance: "112", police: "113" },
  { country: "Maldives", countryAr: "المالديف", flag: "🇲🇻", region: "asia", emergency: "119", ambulance: "102", police: "119" },
  { country: "China", countryAr: "الصين", flag: "🇨🇳", region: "asia", emergency: "120", ambulance: "120", police: "110", fire: "119" },
  { country: "Japan", countryAr: "اليابان", flag: "🇯🇵", region: "asia", emergency: "119", ambulance: "119", police: "110" },
  { country: "South Korea", countryAr: "كوريا الجنوبية", flag: "🇰🇷", region: "asia", emergency: "112", ambulance: "119", police: "112", fire: "119" },
  { country: "North Korea", countryAr: "كوريا الشمالية", flag: "🇰🇵", region: "asia", emergency: "119" },
  { country: "Mongolia", countryAr: "منغوليا", flag: "🇲🇳", region: "asia", emergency: "105", ambulance: "103", police: "102", fire: "101" },
  { country: "Taiwan", countryAr: "تايوان", flag: "🇹🇼", region: "asia", emergency: "112", ambulance: "119", police: "110", fire: "119" },
  { country: "Hong Kong", countryAr: "هونغ كونغ", flag: "🇭🇰", region: "asia", emergency: "999" },
  { country: "Vietnam", countryAr: "فيتنام", flag: "🇻🇳", region: "asia", emergency: "113", ambulance: "115", police: "113", fire: "114" },
  { country: "Thailand", countryAr: "تايلاند", flag: "🇹🇭", region: "asia", emergency: "191", ambulance: "1669", police: "191" },
  { country: "Cambodia", countryAr: "كمبوديا", flag: "🇰🇭", region: "asia", emergency: "117", ambulance: "119", police: "117", fire: "118" },
  { country: "Laos", countryAr: "لاوس", flag: "🇱🇦", region: "asia", emergency: "191", ambulance: "195", police: "191", fire: "190" },
  { country: "Myanmar", countryAr: "ميانمار", flag: "🇲🇲", region: "asia", emergency: "199", ambulance: "192", police: "199", fire: "191" },
  { country: "Malaysia", countryAr: "ماليزيا", flag: "🇲🇾", region: "asia", emergency: "999", ambulance: "999" },
  { country: "Singapore", countryAr: "سنغافورة", flag: "🇸🇬", region: "asia", emergency: "999", ambulance: "995", fire: "995" },
  { country: "Indonesia", countryAr: "إندونيسيا", flag: "🇮🇩", region: "asia", emergency: "112", ambulance: "118", police: "110", fire: "113" },
  { country: "Philippines", countryAr: "الفلبين", flag: "🇵🇭", region: "asia", emergency: "911" },
  { country: "Brunei", countryAr: "بروناي", flag: "🇧🇳", region: "asia", emergency: "991", ambulance: "991", police: "993", fire: "995" },
  { country: "Timor-Leste", countryAr: "تيمور الشرقية", flag: "🇹🇱", region: "asia", emergency: "112" },
  { country: "Kazakhstan", countryAr: "كازاخستان", flag: "🇰🇿", region: "asia", emergency: "112", ambulance: "103", police: "102", fire: "101" },
  { country: "Uzbekistan", countryAr: "أوزبكستان", flag: "🇺🇿", region: "asia", emergency: "112", ambulance: "103", police: "102", fire: "101" },
  { country: "Turkmenistan", countryAr: "تركمانستان", flag: "🇹🇲", region: "asia", emergency: "03", ambulance: "03", police: "02", fire: "01" },
  { country: "Kyrgyzstan", countryAr: "قيرغيزستان", flag: "🇰🇬", region: "asia", emergency: "112" },
  { country: "Tajikistan", countryAr: "طاجيكستان", flag: "🇹🇯", region: "asia", emergency: "112" },

  // ===== AMERICAS =====
  { country: "United States", countryAr: "الولايات المتحدة", flag: "🇺🇸", region: "americas", emergency: "911", mentalCrisis: "988", poison: "1-800-222-1222" },
  { country: "Canada", countryAr: "كندا", flag: "🇨🇦", region: "americas", emergency: "911", mentalCrisis: "988" },
  { country: "Mexico", countryAr: "المكسيك", flag: "🇲🇽", region: "americas", emergency: "911" },
  { country: "Guatemala", countryAr: "غواتيمالا", flag: "🇬🇹", region: "americas", emergency: "110", ambulance: "125", police: "110", fire: "123" },
  { country: "Belize", countryAr: "بليز", flag: "🇧🇿", region: "americas", emergency: "911" },
  { country: "El Salvador", countryAr: "السلفادور", flag: "🇸🇻", region: "americas", emergency: "911" },
  { country: "Honduras", countryAr: "هندوراس", flag: "🇭🇳", region: "americas", emergency: "911" },
  { country: "Nicaragua", countryAr: "نيكاراغوا", flag: "🇳🇮", region: "americas", emergency: "118", ambulance: "128", police: "118" },
  { country: "Costa Rica", countryAr: "كوستاريكا", flag: "🇨🇷", region: "americas", emergency: "911" },
  { country: "Panama", countryAr: "بنما", flag: "🇵🇦", region: "americas", emergency: "911", ambulance: "911", police: "104", fire: "103" },
  { country: "Cuba", countryAr: "كوبا", flag: "🇨🇺", region: "americas", emergency: "106", ambulance: "104", police: "106", fire: "105" },
  { country: "Jamaica", countryAr: "جامايكا", flag: "🇯🇲", region: "americas", emergency: "119", ambulance: "110", police: "119", fire: "110" },
  { country: "Haiti", countryAr: "هايتي", flag: "🇭🇹", region: "americas", emergency: "114", ambulance: "116", police: "114" },
  { country: "Dominican Republic", countryAr: "الدومينيكان", flag: "🇩🇴", region: "americas", emergency: "911" },
  { country: "Bahamas", countryAr: "الباهاما", flag: "🇧🇸", region: "americas", emergency: "911", ambulance: "919" },
  { country: "Trinidad and Tobago", countryAr: "ترينيداد وتوباغو", flag: "🇹🇹", region: "americas", emergency: "999", ambulance: "990", police: "999" },
  { country: "Barbados", countryAr: "بربادوس", flag: "🇧🇧", region: "americas", emergency: "211", ambulance: "511", police: "211", fire: "311" },
  { country: "Brazil", countryAr: "البرازيل", flag: "🇧🇷", region: "americas", emergency: "192", ambulance: "192", police: "190", fire: "193", mentalCrisis: "188" },
  { country: "Argentina", countryAr: "الأرجنتين", flag: "🇦🇷", region: "americas", emergency: "911", ambulance: "107", police: "911", fire: "100" },
  { country: "Chile", countryAr: "تشيلي", flag: "🇨🇱", region: "americas", emergency: "133", ambulance: "131", police: "133", fire: "132" },
  { country: "Peru", countryAr: "بيرو", flag: "🇵🇪", region: "americas", emergency: "105", ambulance: "117", police: "105", fire: "116" },
  { country: "Colombia", countryAr: "كولومبيا", flag: "🇨🇴", region: "americas", emergency: "123" },
  { country: "Venezuela", countryAr: "فنزويلا", flag: "🇻🇪", region: "americas", emergency: "171" },
  { country: "Ecuador", countryAr: "الإكوادور", flag: "🇪🇨", region: "americas", emergency: "911" },
  { country: "Bolivia", countryAr: "بوليفيا", flag: "🇧🇴", region: "americas", emergency: "110", ambulance: "118", police: "110", fire: "119" },
  { country: "Paraguay", countryAr: "باراغواي", flag: "🇵🇾", region: "americas", emergency: "911", ambulance: "141", fire: "132" },
  { country: "Uruguay", countryAr: "أوروغواي", flag: "🇺🇾", region: "americas", emergency: "911", ambulance: "105", police: "911", fire: "104" },
  { country: "Guyana", countryAr: "غيانا", flag: "🇬🇾", region: "americas", emergency: "911", ambulance: "913" },
  { country: "Suriname", countryAr: "سورينام", flag: "🇸🇷", region: "americas", emergency: "115", police: "115" },

  // ===== OCEANIA =====
  { country: "Australia", countryAr: "أستراليا", flag: "🇦🇺", region: "oceania", emergency: "000", mentalCrisis: "131114" },
  { country: "New Zealand", countryAr: "نيوزيلندا", flag: "🇳🇿", region: "oceania", emergency: "111", mentalCrisis: "1737" },
  { country: "Fiji", countryAr: "فيجي", flag: "🇫🇯", region: "oceania", emergency: "911", ambulance: "911", police: "917", fire: "910" },
  { country: "Papua New Guinea", countryAr: "بابوا غينيا الجديدة", flag: "🇵🇬", region: "oceania", emergency: "111", ambulance: "111", police: "112" },
  { country: "Solomon Islands", countryAr: "جزر سليمان", flag: "🇸🇧", region: "oceania", emergency: "999" },
  { country: "Vanuatu", countryAr: "فانواتو", flag: "🇻🇺", region: "oceania", emergency: "112", ambulance: "112", police: "111", fire: "113" },
  { country: "Samoa", countryAr: "ساموا", flag: "🇼🇸", region: "oceania", emergency: "911", ambulance: "996", police: "995", fire: "994" },
  { country: "Tonga", countryAr: "تونغا", flag: "🇹🇴", region: "oceania", emergency: "911", ambulance: "933", police: "922", fire: "999" },
  { country: "Kiribati", countryAr: "كيريباتي", flag: "🇰🇮", region: "oceania", emergency: "999", ambulance: "994", police: "192", fire: "193" },
  { country: "Tuvalu", countryAr: "توفالو", flag: "🇹🇻", region: "oceania", emergency: "911" },
  { country: "Nauru", countryAr: "ناورو", flag: "🇳🇷", region: "oceania", emergency: "110", ambulance: "111", police: "110", fire: "112" },
  { country: "Palau", countryAr: "بالاو", flag: "🇵🇼", region: "oceania", emergency: "911" },
  { country: "Marshall Islands", countryAr: "جزر مارشال", flag: "🇲🇭", region: "oceania", emergency: "911" },
  { country: "Micronesia", countryAr: "ميكرونيزيا", flag: "🇫🇲", region: "oceania", emergency: "911" },
];

export const REGIONS: { id: EmergencyContact["region"]; ar: string; en: string }[] = [
  { id: "arab", ar: "الدول العربية", en: "Arab Countries" },
  { id: "africa", ar: "أفريقيا", en: "Africa" },
  { id: "asia", ar: "آسيا", en: "Asia" },
  { id: "europe", ar: "أوروبا", en: "Europe" },
  { id: "americas", ar: "الأمريكتين", en: "Americas" },
  { id: "oceania", ar: "أوقيانوسيا", en: "Oceania" },
];
