import type { Disease } from "./diseases";

const d = (
  id: string,
  category: Disease["category"],
  severity: Disease["severity"],
  ar: { name: string; shortDesc: string; symptoms: string[]; causes: string[]; treatments: string[]; research?: string; whatToDo?: string },
  en: { name: string; shortDesc: string; symptoms: string[]; causes: string[]; treatments: string[]; research?: string; whatToDo?: string },
): Disease => ({ id, category, severity, ar, en });

// Additional diseases — mostly mental + a few common.
export const extraDiseases: Disease[] = [
  d("ptsd", "mental", "severe",
    { name: "اضطراب ما بعد الصدمة (PTSD)", shortDesc: "ردود فعل نفسية وجسدية شديدة بعد صدمة كبيرة (حادث، اعتداء، حرب).",
      symptoms: ["استرجاع الذكريات (Flashbacks)", "كوابيس متكررة", "تجنّب الأماكن المرتبطة بالحدث", "فرط التيقّظ والإجفال", "انفصال عاطفي", "صعوبة نوم وتركيز"],
      causes: ["تعرّض مباشر/شهادة على حدث صادم", "غياب الدعم بعد الصدمة", "صدمات سابقة بالطفولة"],
      treatments: ["العلاج بإعادة معالجة الذكريات (EMDR)", "العلاج المعرفي السلوكي للصدمة (TF-CBT)", "مضادات اكتئاب SSRI (سيرترالين/باروكستين)", "Prazosin للكوابيس"],
      research: "علاج بالـ MDMA-assisted therapy في تجارب المرحلة 3.",
      whatToDo: "إذا ظهرت الأعراض لأكثر من شهر بعد الحدث، احجز معالج نفسي متخصص في الصدمات." },
    { name: "Post-Traumatic Stress Disorder (PTSD)", shortDesc: "Severe psychological & physical reactions after a major trauma.",
      symptoms: ["Flashbacks", "Recurrent nightmares", "Avoidance of triggers", "Hyper-vigilance & startle", "Emotional numbing", "Sleep & focus issues"],
      causes: ["Direct/witnessed traumatic event", "Lack of post-trauma support", "Childhood trauma history"],
      treatments: ["EMDR", "Trauma-focused CBT", "SSRIs (sertraline/paroxetine)", "Prazosin for nightmares"],
      research: "MDMA-assisted therapy in Phase 3 trials.",
      whatToDo: "If symptoms persist >1 month after the event, see a trauma-trained psychotherapist." }),

  d("ocd", "mental", "moderate",
    { name: "الوسواس القهري (OCD)", shortDesc: "أفكار متطفّلة (وسواس) وأفعال متكررة (قهر) للتخفيف من القلق.",
      symptoms: ["خوف شديد من التلوث", "غسيل يدين متكرر", "فحص الأبواب والمفاتيح مراراً", "ترتيب الأشياء بشكل مُنظَّم جداً", "أفكار عدوانية أو دينية مزعجة"],
      causes: ["وراثة", "خلل في السيروتونين", "ضغوط أو صدمة", "التهاب مناعي بعد عدوى (PANDAS عند الأطفال)"],
      treatments: ["العلاج بالتعرض ومنع الاستجابة (ERP)", "SSRI بجرعات عالية (فلوكستين، فلوفوكسامين)", "كلوميبرامين كخيار ثانٍ", "TMS للحالات المقاومة"],
      research: "DBS (تحفيز عميق بالمخ) للحالات الشديدة جداً.",
      whatToDo: "ERP أكثر علاج فعّال — اطلب معالج CBT متخصص فيه." },
    { name: "Obsessive-Compulsive Disorder (OCD)", shortDesc: "Intrusive thoughts (obsessions) + repetitive acts (compulsions) to relieve anxiety.",
      symptoms: ["Contamination fears", "Excessive hand-washing", "Repeated checking", "Symmetry/ordering", "Distressing aggressive/religious thoughts"],
      causes: ["Genetics", "Serotonin imbalance", "Stress/trauma", "Post-infectious autoimmune (PANDAS in children)"],
      treatments: ["Exposure & Response Prevention (ERP)", "High-dose SSRIs", "Clomipramine", "TMS for resistant cases"],
      research: "Deep brain stimulation (DBS) for severe cases.",
      whatToDo: "ERP is the most effective therapy — find a CBT-trained specialist." }),

  d("adhd", "mental", "moderate",
    { name: "اضطراب فرط الحركة وتشتت الانتباه (ADHD)", shortDesc: "صعوبة مزمنة في التركيز و/أو الاندفاعية وفرط الحركة.",
      symptoms: ["صعوبة إكمال المهام", "نسيان متكرر", "تململ مستمر", "كلام مفرط", "مقاطعة الآخرين", "صعوبة الانتظار"],
      causes: ["وراثة قوية (~75%)", "خلل في الدوبامين", "عوامل بيئية قبل الولادة"],
      treatments: ["منشطات (ميثيل فينيدات/أمفيتامين)", "أدوية غير منشطة (أتوموكسيتين)", "علاج سلوكي معرفي", "تنظيم بيئي ومدرسي"],
      research: "الواقع الافتراضي للتأهيل المعرفي.",
      whatToDo: "تشخيص يحتاج طبيب نفسي (اطفال أو بالغين) — لا تشخّص ذاتياً." },
    { name: "ADHD", shortDesc: "Chronic difficulty with focus and/or impulsivity & hyperactivity.",
      symptoms: ["Trouble finishing tasks", "Forgetfulness", "Restlessness", "Excessive talking", "Interrupting", "Trouble waiting"],
      causes: ["Strong genetics (~75%)", "Dopamine dysregulation", "Prenatal factors"],
      treatments: ["Stimulants (methylphenidate/amphetamine)", "Non-stimulants (atomoxetine)", "Behavioral CBT", "Environmental scaffolding"],
      research: "VR-based cognitive training.",
      whatToDo: "Diagnosis requires a psychiatrist — don't self-diagnose." }),

  d("bipolar", "mental", "severe",
    { name: "الاضطراب ثنائي القطب", shortDesc: "تقلبات شديدة بين هوس (طاقة عالية) واكتئاب (طاقة منخفضة).",
      symptoms: ["نوبات هوس: قلة نوم، أفكار متسارعة، إنفاق مفرط", "نوبات اكتئاب: حزن، يأس، فقدان الاهتمام", "اندفاعية", "تغيرات حادة في الشهية والوزن"],
      causes: ["وراثة قوية", "خلل كيمياء المخ", "مُحفّزات: قلة نوم، توتر، تعاطي"],
      treatments: ["مثبتات المزاج (الليثيوم، فالبروات)", "مضادات ذهان لا نمطية (كويتيابين)", "لاموتريجين للاكتئاب", "علاج نفسي IPSRT", "تنظيم نوم صارم"],
      research: "بحوث جينات CACNA1C.",
      whatToDo: "إذا لاحظت دورات حادة من ارتفاع/انخفاض المزاج اطلب طبيب نفسي فوراً." },
    { name: "Bipolar Disorder", shortDesc: "Severe swings between mania (high energy) and depression.",
      symptoms: ["Mania: little sleep, racing thoughts, overspending", "Depression: hopelessness, anhedonia", "Impulsivity", "Appetite/weight changes"],
      causes: ["Strong genetics", "Brain chemistry imbalance", "Triggers: sleep loss, stress, substance use"],
      treatments: ["Mood stabilizers (lithium, valproate)", "Atypical antipsychotics (quetiapine)", "Lamotrigine for depression", "IPSRT therapy", "Strict sleep schedule"],
      research: "CACNA1C gene research.",
      whatToDo: "Consult a psychiatrist immediately if you notice extreme mood cycles." }),

  d("borderline", "mental", "severe",
    { name: "اضطراب الشخصية الحدّية (BPD)", shortDesc: "عدم استقرار شديد بالمشاعر والعلاقات والهوية.",
      symptoms: ["خوف شديد من الهجر", "علاقات متذبذبة (مثالية ↔ كراهية)", "اندفاع: قيادة، إنفاق، طعام، جنس", "إيذاء ذاتي", "شعور مزمن بالفراغ", "غضب شديد"],
      causes: ["صدمات طفولة", "وراثة جزئية", "اضطراب تنظيم العاطفة"],
      treatments: ["العلاج الجدلي السلوكي (DBT) — الأكثر فاعلية", "العلاج القائم على التمنيل (MBT)", "أدوية للأعراض المصاحبة (مضاد ذهان جرعة منخفضة)"],
      research: "علاج Schema Therapy لتعديل الأنماط.",
      whatToDo: "ابحث عن معالج معتمد في DBT." },
    { name: "Borderline Personality Disorder (BPD)", shortDesc: "Severe instability in mood, relationships, and identity.",
      symptoms: ["Intense fear of abandonment", "Unstable relationships (idealize↔devalue)", "Impulsivity", "Self-harm", "Chronic emptiness", "Intense anger"],
      causes: ["Childhood trauma", "Partial genetics", "Emotion-regulation disorder"],
      treatments: ["DBT (most effective)", "MBT therapy", "Low-dose meds for symptoms"],
      research: "Schema Therapy for pattern modification.",
      whatToDo: "Find a DBT-certified therapist." }),

  d("eating-disorder", "mental", "severe",
    { name: "اضطرابات الأكل (فقدان الشهية / النَهَم)", shortDesc: "علاقة مرضية مع الطعام وصورة الجسم تُهدّد الصحة.",
      symptoms: ["خوف شديد من زيادة الوزن", "تقييد طعام شديد أو نوبات شراهة", "تقيؤ متعمَّد أو رياضة مفرطة", "اضطراب صورة الجسم", "تساقط شعر، انقطاع طمث"],
      causes: ["ضغوط ثقافية وجمالية", "وراثة", "صدمات", "اضطراب قلق مصاحب"],
      treatments: ["علاج عائلي (FBT) للمراهقين", "CBT-E", "إعادة تأهيل تغذوي تحت إشراف", "SSRI للنَهَم"],
      research: "أدوية GLP-1 وعلاجات نوروبيولوجية للجوع.",
      whatToDo: "BMI أقل من 17 أو تقيؤ متكرر = طوارئ — احجز مع طبيب نفسي وأخصائي تغذية." },
    { name: "Eating Disorders (Anorexia / Bulimia)", shortDesc: "Pathological relationship with food and body image.",
      symptoms: ["Intense fear of weight gain", "Severe restriction or binging", "Self-induced vomiting / over-exercise", "Body-image distortion", "Hair loss, amenorrhea"],
      causes: ["Cultural pressure", "Genetics", "Trauma", "Co-occurring anxiety"],
      treatments: ["Family-Based Therapy (FBT) for teens", "CBT-E", "Supervised re-feeding", "SSRIs for bulimia"],
      research: "GLP-1 & neurobiological hunger therapies.",
      whatToDo: "BMI <17 or repeated vomiting = emergency. See psychiatrist + dietitian." }),

  d("schizophrenia", "mental", "critical",
    { name: "الفصام (Schizophrenia)", shortDesc: "اضطراب ذهاني يسبب هلاوس وأوهام واضطراب التفكير.",
      symptoms: ["هلاوس سمعية (سماع أصوات)", "أوهام (اعتقاد غير حقيقي قوي)", "تفكير مشتت", "انسحاب اجتماعي", "تسطّح عاطفي"],
      causes: ["وراثة قوية", "خلل دوبامين/جلوتامات", "إجهاد أو تعاطي يحفّز النوبة", "مضاعفات حمل"],
      treatments: ["مضادات ذهان (ريسبيريدون، أولانزابين، كلوزابين للحالات المقاومة)", "علاج نفسي اجتماعي وتأهيل مهني", "دعم عائلي"],
      research: "علاج xanomeline-trospium (KarXT) كآلية جديدة.",
      whatToDo: "أي ذهان = طبيب نفسي عاجل. التشخيص المبكر يحسّن المسار جداً." },
    { name: "Schizophrenia", shortDesc: "Psychotic disorder with hallucinations, delusions, and disorganized thinking.",
      symptoms: ["Auditory hallucinations", "Delusions", "Disorganized thinking", "Social withdrawal", "Flat affect"],
      causes: ["Strong genetics", "Dopamine/glutamate imbalance", "Stress/substance trigger", "Birth complications"],
      treatments: ["Antipsychotics (risperidone, olanzapine, clozapine for resistant)", "Psychosocial therapy & vocational rehab", "Family support"],
      research: "Xanomeline-trospium (KarXT) novel mechanism.",
      whatToDo: "Any psychosis = urgent psychiatry referral." }),

  d("social-anxiety", "mental", "moderate",
    { name: "اضطراب القلق الاجتماعي", shortDesc: "خوف شديد من المواقف الاجتماعية والحكم من الآخرين.",
      symptoms: ["خوف شديد من الكلام أمام الناس", "احمرار، تعرّق، رعشة", "تجنب اللقاءات", "قلق مسبق بأيام"],
      causes: ["وراثة", "تجارب إحراج مبكرة", "تربية ناقدة"],
      treatments: ["CBT مع تعرّض تدريجي", "SSRI (سيرترالين، باروكستين)", "بيتا-بلوكر (بروبرانولول) للأعراض الحادة قبل المواقف"],
      research: "علاج بالواقع الافتراضي.",
      whatToDo: "ابدأ بـ CBT — فعّال جداً خلال 12-16 جلسة." },
    { name: "Social Anxiety Disorder", shortDesc: "Intense fear of social situations and judgment.",
      symptoms: ["Fear of public speaking", "Blushing, sweating, trembling", "Avoidance", "Anticipatory anxiety"],
      causes: ["Genetics", "Early embarrassment", "Critical parenting"],
      treatments: ["CBT with gradual exposure", "SSRIs", "Beta-blockers (propranolol) before specific events"],
      research: "VR exposure therapy.",
      whatToDo: "Start with CBT — highly effective in 12-16 sessions." }),

  d("panic-disorder", "mental", "moderate",
    { name: "اضطراب الهلع (Panic Disorder)", shortDesc: "نوبات هلع مفاجئة شديدة تشبه أزمة قلبية.",
      symptoms: ["خفقان شديد", "ضيق نفس", "تنميل", "دوخة، شعور بالموت", "خوف من نوبة جديدة"],
      causes: ["حساسية للقلق", "وراثة", "إجهاد مزمن"],
      treatments: ["CBT للهلع", "SSRI", "بنزوديازيبين قصير المدى فقط للأزمات"],
      research: "تطبيقات تنفس إيقاعي مدعومة بحيوي حيوي.",
      whatToDo: "أول نوبة → استبعد قلب أولاً (تخطيط ECG)، ثم احجز نفسي." },
    { name: "Panic Disorder", shortDesc: "Sudden severe panic attacks resembling a heart attack.",
      symptoms: ["Heart palpitations", "Shortness of breath", "Numbness", "Dizziness, fear of dying", "Anticipatory fear"],
      causes: ["Anxiety sensitivity", "Genetics", "Chronic stress"],
      treatments: ["Panic-focused CBT", "SSRIs", "Short-term benzodiazepines for crises only"],
      research: "Biofeedback breathing apps.",
      whatToDo: "First attack → rule out cardiac (ECG) first, then see psychiatrist." }),

  d("postpartum-depression", "mental", "severe",
    { name: "اكتئاب ما بعد الولادة", shortDesc: "اكتئاب يصيب 10-15% من الأمهات بعد الولادة.",
      symptoms: ["حزن مستمر", "بكاء بدون سبب", "صعوبة الترابط مع الطفل", "قلق حول صحته", "أفكار إيذاء النفس أو الطفل (نادر)"],
      causes: ["تغيرات هرمونية", "قلة نوم", "تاريخ اكتئاب سابق", "نقص دعم اجتماعي"],
      treatments: ["علاج نفسي (CBT/IPT)", "SSRIs آمنة للرضاعة (سيرترالين)", "Brexanolone/Zuranolone حديث للحالات الشديدة"],
      research: "علاج Zuranolone عبر الفم.",
      whatToDo: "إذا أعراض > أسبوعين بعد الولادة، احجز فوراً. أي أفكار إيذاء = طوارئ." },
    { name: "Postpartum Depression", shortDesc: "Affects 10-15% of mothers after childbirth.",
      symptoms: ["Persistent sadness", "Crying without reason", "Difficulty bonding", "Anxiety about baby", "Self/baby harm thoughts (rare)"],
      causes: ["Hormonal shifts", "Sleep deprivation", "Past depression", "Low social support"],
      treatments: ["CBT/IPT", "Breastfeeding-safe SSRIs (sertraline)", "Brexanolone/Zuranolone for severe"],
      research: "Oral Zuranolone.",
      whatToDo: "If symptoms >2 weeks postpartum, see provider. Any harm thoughts = emergency." }),

  d("autism-adults", "mental", "moderate",
    { name: "طيف التوحد لدى البالغين", shortDesc: "تشخيص متأخر شائع لدى من تجاوزوا مرحلة الطفولة.",
      symptoms: ["صعوبة قراءة الإشارات الاجتماعية", "اهتمامات عميقة محددة", "حساسية حسية", "روتين صارم", "إرهاق اجتماعي"],
      causes: ["وراثة", "نمو عصبي مختلف"],
      treatments: ["تأهيل اجتماعي", "علاج وظيفي حسي", "علاج للقلق/الاكتئاب المصاحب"],
      research: "بحوث حول اختلافات الدماغ التركيبية.",
      whatToDo: "للتشخيص: طبيب نفسي متخصص في النمو العصبي للبالغين." },
    { name: "Autism in Adults", shortDesc: "Often diagnosed later in life.",
      symptoms: ["Difficulty reading social cues", "Deep specific interests", "Sensory sensitivities", "Rigid routines", "Social fatigue"],
      causes: ["Genetics", "Different neurodevelopment"],
      treatments: ["Social rehabilitation", "Sensory OT", "Treat co-occurring anxiety/depression"],
      research: "Brain structural differences.",
      whatToDo: "Adult-developmental psychiatrist for diagnosis." }),

  // A few common physical ones not yet present
  d("migraine", "common", "moderate",
    { name: "الصداع النصفي (Migraine)", shortDesc: "صداع شديد نابض غالباً في جانب واحد مع غثيان وحساسية للضوء.",
      symptoms: ["صداع نابض شديد", "غثيان وقيء", "حساسية للضوء والصوت", "هالة بصرية أحياناً"],
      causes: ["وراثة", "محفّزات: قهوة، شوكولاتة، نقص نوم، توتر، تغيرات هرمونية"],
      treatments: ["تريبتانز (سوماتريبتان)", "وقاية: بيتا-بلوكر، توبيراميت، CGRP-inhibitors (إيرينوماب)", "تجنّب المحفّزات"],
      research: "علاجات CGRP الحديثة فعالة جداً للوقاية.",
      whatToDo: "إذا أكثر من 4 نوبات شهرياً، اطلب علاج وقائي." },
    { name: "Migraine", shortDesc: "Severe pulsating one-sided headache with nausea & light sensitivity.",
      symptoms: ["Pulsating headache", "Nausea/vomiting", "Light/sound sensitivity", "Visual aura sometimes"],
      causes: ["Genetics", "Triggers: caffeine, chocolate, sleep loss, stress, hormones"],
      treatments: ["Triptans", "Prevention: beta-blockers, topiramate, CGRP inhibitors (erenumab)", "Avoid triggers"],
      research: "Modern CGRP therapies highly effective.",
      whatToDo: "If >4 attacks/month, request preventive treatment." }),

  d("ibs", "common", "moderate",
    { name: "القولون العصبي (IBS)", shortDesc: "اضطراب وظيفي مزمن بالأمعاء يسبب آلام وانتفاخ وتغير عادات الإخراج.",
      symptoms: ["آلام بطن مع تغير الإخراج", "انتفاخ وغازات", "إسهال أو إمساك أو تبادل بينهما", "شعور بعدم اكتمال التبرّز"],
      causes: ["خلل في محور الأمعاء-الدماغ", "حساسية لأطعمة (FODMAP)", "توتر", "تغيرات بكتيريا الأمعاء"],
      treatments: ["نظام Low-FODMAP", "ألياف ذائبة (سيلليوم)", "موسّعات معوية (mebeverine)", "بروبيوتيك", "مضادات اكتئاب جرعة منخفضة لتعديل ألم"],
      research: "أبحاث في FMT وزراعة الميكروبيوم.",
      whatToDo: "نزف، نقص وزن، أعراض ليلية = ليس IBS، اعمل منظار." },
    { name: "Irritable Bowel Syndrome (IBS)", shortDesc: "Chronic functional bowel disorder.",
      symptoms: ["Abdominal pain with bowel changes", "Bloating", "Diarrhea/constipation/alternating", "Incomplete evacuation"],
      causes: ["Gut-brain axis dysfunction", "FODMAP sensitivity", "Stress", "Microbiome shifts"],
      treatments: ["Low-FODMAP diet", "Soluble fiber (psyllium)", "Antispasmodics (mebeverine)", "Probiotics", "Low-dose antidepressants for pain"],
      research: "Microbiome FMT trials.",
      whatToDo: "Bleeding, weight loss, night symptoms = not IBS — get scope." }),
];
