import type { Disease } from "./diseases";

const d = (
  id: string,
  category: Disease["category"],
  severity: Disease["severity"],
  ar: { name: string; shortDesc: string; symptoms: string[]; causes: string[]; treatments: string[]; research?: string; whatToDo?: string },
  en: { name: string; shortDesc: string; symptoms: string[]; causes: string[]; treatments: string[]; research?: string; whatToDo?: string },
): Disease => ({ id, category, severity, ar, en });

// Additional PHYSICAL (non-mental) diseases.
export const physicalDiseases: Disease[] = [
  d("hypothyroidism", "common", "moderate",
    { name: "قصور الغدة الدرقية", shortDesc: "نقص هرمونات الغدة يسبب بطء في وظائف الجسم.",
      symptoms: ["إرهاق مستمر", "زيادة وزن غير مبررة", "حساسية للبرد", "إمساك", "جفاف جلد وتساقط شعر", "اكتئاب وبطء تفكير", "اضطراب دورة شهرية"],
      causes: ["التهاب هاشيموتو المناعي", "نقص يود", "بعد جراحة أو علاج إشعاعي للغدة", "أدوية (ليثيوم، أميودارون)"],
      treatments: ["ليفوثيروكسين يومياً صباحاً قبل الأكل بنصف ساعة", "متابعة TSH كل 6-8 أسابيع حتى الاستقرار"],
      research: "أبحاث في علاج مركّب T3+T4 لمرضى لا يستجيبون لـ T4 وحده.",
      whatToDo: "حلل TSH و Free T4 — إذا TSH مرتفع، ابدأ علاج ومتابعة." },
    { name: "Hypothyroidism", shortDesc: "Underactive thyroid slows bodily functions.",
      symptoms: ["Persistent fatigue", "Unexplained weight gain", "Cold intolerance", "Constipation", "Dry skin/hair loss", "Depression & slow thinking", "Menstrual changes"],
      causes: ["Hashimoto's autoimmune", "Iodine deficiency", "Post-thyroid surgery/radiation", "Drugs (lithium, amiodarone)"],
      treatments: ["Daily levothyroxine (morning, 30 min before food)", "Recheck TSH every 6-8 weeks until stable"],
      research: "Combination T3+T4 therapy for non-responders.",
      whatToDo: "Order TSH + Free T4 — if TSH high, start treatment & monitor." }),

  d("hyperthyroidism", "common", "moderate",
    { name: "فرط نشاط الغدة الدرقية", shortDesc: "زيادة هرمونات الغدة تُسرّع وظائف الجسم.",
      symptoms: ["خفقان وتسرع نبض", "نقص وزن مع زيادة شهية", "رعشة يدين", "تعرّق وعدم تحمّل حرارة", "عصبية وأرق", "جحوظ عينين (في غريفز)"],
      causes: ["مرض غريفز المناعي", "عقيدات سامة", "التهاب درقي", "زيادة جرعة ليفوثيروكسين"],
      treatments: ["كاربيمازول/ميثيمازول", "حاصرات بيتا (بروبرانولول) لتسكين الأعراض", "يود مشع أو جراحة في الحالات المقاومة"],
      whatToDo: "حلل TSH (يكون منخفض جداً) و Free T4/T3. زر استشاري غدد فوراً." },
    { name: "Hyperthyroidism", shortDesc: "Overactive thyroid speeds up body functions.",
      symptoms: ["Palpitations & tachycardia", "Weight loss with increased appetite", "Hand tremor", "Sweating, heat intolerance", "Nervousness & insomnia", "Eye bulging (Graves')"],
      causes: ["Graves' disease (autoimmune)", "Toxic nodules", "Thyroiditis", "Levothyroxine over-replacement"],
      treatments: ["Carbimazole/methimazole", "Beta-blockers for symptoms", "Radioactive iodine or surgery for resistant cases"],
      whatToDo: "Check TSH (very low) + Free T4/T3, see endocrinologist." }),

  d("anemia-iron", "common", "moderate",
    { name: "أنيميا نقص الحديد", shortDesc: "نقص الحديد يقلل الهيموجلوبين فيظهر تعب وشحوب.",
      symptoms: ["إرهاق وضعف", "شحوب جلد وأظافر", "ضيق نفس عند المجهود", "خفقان", "تساقط شعر", "تكسّر أظافر", "بيكا (شهية لأشياء غريبة كالطين)"],
      causes: ["نزف دورة شهرية غزيرة", "نزف هضمي خفي (قرحة، بواسير، أورام)", "سوء امتصاص (سيلياك)", "نظام غذائي فقير", "حمل ورضاعة"],
      treatments: ["حديد فموي (سلفات حديد 60-200 مج عنصري) مع فيتامين C", "حقن وريدية إذا فشل الفموي", "علاج السبب الأصلي"],
      whatToDo: "إذا CBC أظهرت Hb منخفض و MCV منخفض → اطلب فيريتين، وابحث عن مصدر النزف عند الكبار." },
    { name: "Iron-Deficiency Anemia", shortDesc: "Low iron drops hemoglobin → fatigue, pallor.",
      symptoms: ["Fatigue & weakness", "Pale skin/nails", "Exertional dyspnea", "Palpitations", "Hair loss", "Brittle nails", "Pica (craving non-food)"],
      causes: ["Heavy menses", "Occult GI bleed (ulcer, hemorrhoids, cancer)", "Malabsorption (celiac)", "Poor diet", "Pregnancy/lactation"],
      treatments: ["Oral ferrous sulfate 60-200 mg elemental + vit C", "IV iron if oral fails", "Treat underlying cause"],
      whatToDo: "Low Hb + low MCV → check ferritin; in adults, hunt for GI bleed source." }),

  d("hypertension", "common", "severe",
    { name: "ارتفاع ضغط الدم", shortDesc: "ضغط دائم ≥140/90 بدون أعراض غالباً (القاتل الصامت).",
      symptoms: ["غالباً بدون أعراض", "صداع خلفي", "دوخة", "نزيف أنف", "رؤية ضبابية في الحالات الشديدة"],
      causes: ["وراثة", "ملح زائد، سمنة، خمول", "تدخين وكحول", "أمراض كلى أو غدة (ثانوي)"],
      treatments: ["تقليل ملح < 5جم/يوم", "نشاط 150 دقيقة/أسبوع", "ACE inhibitors / ARBs / حاصرات كالسيوم / ثيازيد", "تخفيض وزن"],
      research: "أهداف أكثر صرامة <120 (دراسة SPRINT) لمرضى عالية الخطر.",
      whatToDo: "قِس ضغطك مرتين أسبوعياً. ضغط ≥180/120 = طوارئ." },
    { name: "Hypertension", shortDesc: "Persistent BP ≥140/90, often silent ('silent killer').",
      symptoms: ["Often asymptomatic", "Occipital headache", "Dizziness", "Nosebleed", "Blurred vision in severe"],
      causes: ["Genetics", "High salt, obesity, inactivity", "Smoking & alcohol", "Renal/endocrine (secondary)"],
      treatments: ["Salt <5 g/day", "150 min/week activity", "ACEi / ARB / CCB / thiazide", "Weight loss"],
      research: "Stricter <120 target (SPRINT) in high-risk patients.",
      whatToDo: "Measure BP 2×/week. ≥180/120 = emergency." }),

  d("type2-diabetes", "common", "severe",
    { name: "السكري النوع الثاني", shortDesc: "مقاومة الإنسولين ترفع سكر الدم بشكل مزمن.",
      symptoms: ["كثرة تبول وعطش", "إرهاق", "زغللة عيون", "بطء التئام جروح", "خدر في الأطراف", "زيادة وزن (غالباً)"],
      causes: ["وراثة", "سمنة بطنية", "خمول", "نظام غذائي عالي السكر"],
      treatments: ["نظام غذائي منخفض الكارب", "نشاط بدني 30 دقيقة/يوم", "ميتفورمين خط أول", "GLP-1 (سيماجلوتايد) أو SGLT2 (إمباجليفلوزين)", "إنسولين عند الفشل"],
      research: "علاجات ثنائية مثل tirzepatide تحقق فقدان وزن وضبط سكر معاً.",
      whatToDo: "حلل HbA1c كل 3 شهور. هدف <7%. افحص العين والكلى والقدم سنوياً." },
    { name: "Type 2 Diabetes", shortDesc: "Insulin resistance → chronic hyperglycemia.",
      symptoms: ["Polyuria/polydipsia", "Fatigue", "Blurred vision", "Slow wound healing", "Limb numbness", "Weight gain (often)"],
      causes: ["Genetics", "Central obesity", "Inactivity", "High-sugar diet"],
      treatments: ["Low-carb diet", "30 min/day activity", "Metformin first-line", "GLP-1 (semaglutide) or SGLT2 (empagliflozin)", "Insulin if failing"],
      research: "Dual agonists like tirzepatide achieve weight loss + glycemic control.",
      whatToDo: "HbA1c every 3 months, target <7%. Annual eye/renal/foot screening." }),

  d("gerd", "common", "moderate",
    { name: "ارتجاع المريء (GERD)", shortDesc: "ارتجاع حمض المعدة للمريء يسبب حرقة مزمنة.",
      symptoms: ["حرقة خلف الصدر", "طعم مر بالفم", "كحة ليلية", "بحة صوت صباحاً", "ألم عند البلع", "غثيان"],
      causes: ["ضعف العضلة العاصرة السفلية للمريء", "سمنة، حمل، فتق حجابي", "أكل دسم/حار/قهوة/كحول", "تدخين", "أكلات قبل النوم"],
      treatments: ["ارفع رأس السرير 15 سم", "تجنّب أكل قبل النوم بـ 3 ساعات", "PPI صباحاً (أوميبرازول 20-40 مج)", "H2 blockers", "جراحة Nissen في الحالات المقاومة"],
      whatToDo: "أعراض >8 أسابيع أو صعوبة بلع/نزيف → منظار علوي." },
    { name: "GERD", shortDesc: "Acid reflux into esophagus causing chronic heartburn.",
      symptoms: ["Retrosternal burning", "Bitter taste", "Nocturnal cough", "Morning hoarseness", "Painful swallowing", "Nausea"],
      causes: ["Weak LES", "Obesity, pregnancy, hiatal hernia", "Fatty/spicy/coffee/alcohol", "Smoking", "Late-night meals"],
      treatments: ["Elevate bed head 15 cm", "No food 3h pre-bed", "Morning PPI (omeprazole 20-40 mg)", "H2 blockers", "Nissen fundoplication for resistant"],
      whatToDo: "Symptoms >8 weeks or dysphagia/bleeding → upper endoscopy." }),

  d("uti", "common", "moderate",
    { name: "التهاب المسالك البولية", shortDesc: "عدوى بكتيرية بالمثانة (أو الكلى) شائعة عند النساء.",
      symptoms: ["حرقان وألم عند التبول", "كثرة التبول وإلحاح", "ألم أسفل البطن", "بول عكر برائحة قوية", "دم بالبول أحياناً", "حمى وألم خاصرة (إذا وصل للكلى)"],
      causes: ["E. coli (80%+)", "جنس بدون تفريغ مثانة بعده", "احتباس بول", "حصوات أو قسطرة", "سكري"],
      treatments: ["مضاد حيوي (نيتروفورانتوين 5 أيام أو فوسفوميسين جرعة واحدة)", "اشرب 2-3 لتر ماء يومياً", "علاج الألم بـ phenazopyridine قصير المدى"],
      whatToDo: "حمى ≥38.5 + ألم خاصرة + قيء = عدوى كلى → طوارئ ومضاد حيوي وريدي." },
    { name: "Urinary Tract Infection (UTI)", shortDesc: "Bacterial bladder/kidney infection, common in women.",
      symptoms: ["Burning urination", "Frequency & urgency", "Lower abdominal pain", "Cloudy/foul urine", "Hematuria sometimes", "Fever + flank pain (if pyelonephritis)"],
      causes: ["E. coli (80%+)", "Sex without post-void", "Urinary retention", "Stones/catheter", "Diabetes"],
      treatments: ["Antibiotic (nitrofurantoin 5 days or single-dose fosfomycin)", "2-3 L water/day", "Phenazopyridine for short-term pain"],
      whatToDo: "Fever ≥38.5 + flank pain + vomiting = pyelonephritis → ER + IV antibiotics." }),

  d("osteoarthritis", "common", "moderate",
    { name: "خشونة المفاصل", shortDesc: "تآكل غضروف المفاصل (الركبة، الورك، اليدين) مع التقدم بالعمر.",
      symptoms: ["ألم مفصل يزداد بالحركة ويتحسن بالراحة", "تيبّس صباحي < 30 دقيقة", "طقطقة عند الحركة", "تورم وحرارة خفيفة", "ضيق نطاق حركة"],
      causes: ["تقدم العمر", "وراثة", "سمنة", "إصابات سابقة", "حركات متكررة (عمل/رياضة)"],
      treatments: ["تخفيض وزن (كل 1 كجم = 4 كجم أقل ضغط على الركبة)", "تمارين تقوية عضلة الفخذ الرباعية", "باراسيتامول وNSAIDs (موضعي/فموي)", "حقن كورتيزون أو هيالورونيك للمفصل", "تبديل المفصل في الحالات المتقدمة"],
      whatToDo: "بدء العلاج التحفظي، لو فشل بعد 3 أشهر استشر جرّاح عظام." },
    { name: "Osteoarthritis", shortDesc: "Cartilage wear in knees/hips/hands with age.",
      symptoms: ["Pain with activity, relieved by rest", "Morning stiffness <30 min", "Crepitus", "Swelling/warmth", "Reduced range of motion"],
      causes: ["Aging", "Genetics", "Obesity", "Past injury", "Repetitive use"],
      treatments: ["Weight loss (1 kg = 4 kg less knee load)", "Quadriceps strengthening", "Paracetamol & NSAIDs (topical/oral)", "Intra-articular steroid or hyaluronic injection", "Joint replacement for end-stage"],
      whatToDo: "Start conservative; if no improvement after 3 months, see ortho surgeon." }),

  d("celiac", "common", "moderate",
    { name: "حساسية القمح (السيلياك)", shortDesc: "اضطراب مناعي يسبب تلف الأمعاء عند تناول الجلوتين.",
      symptoms: ["إسهال مزمن أو إمساك", "انتفاخ وغازات", "نقص وزن", "أنيميا حديد لا تتحسن", "هشاشة عظام مبكرة", "تأخر نمو عند الأطفال", "طفح جلدي حكاك (Dermatitis herpetiformis)"],
      causes: ["وراثة (HLA-DQ2/DQ8)", "تعرض للجلوتين (قمح، شعير، شيلم)", "محفّزات بيئية"],
      treatments: ["تجنّب الجلوتين مدى الحياة 100%", "تعويض فيتامينات (D, B12, حديد)", "متابعة أجسام مضادة TTG"],
      whatToDo: "اطلب tTG-IgA + total IgA؛ إذا موجب → منظار وأخذ عينة من الاثني عشر." },
    { name: "Celiac Disease", shortDesc: "Autoimmune gut damage from gluten.",
      symptoms: ["Chronic diarrhea or constipation", "Bloating, gas", "Weight loss", "Iron-deficient anemia not responding", "Early osteoporosis", "Failure to thrive (children)", "Itchy rash (dermatitis herpetiformis)"],
      causes: ["Genetics (HLA-DQ2/DQ8)", "Gluten exposure (wheat, barley, rye)", "Environmental triggers"],
      treatments: ["100% lifelong gluten-free diet", "Replace D, B12, iron", "Follow tTG antibody titers"],
      whatToDo: "Order tTG-IgA + total IgA; if positive → endoscopy with duodenal biopsy." }),

  d("gallstones", "common", "moderate",
    { name: "حصوات المرارة", shortDesc: "حصوات بالمرارة قد تسبب مغصاً شديداً عند انسداد القناة.",
      symptoms: ["ألم شديد مفاجئ تحت الضلع الأيمن (مغص مرارة)", "يمتد للكتف الأيمن أو الظهر", "غثيان وقيء", "ينتج بعد وجبة دسمة", "اصفرار جلد وعينين إذا انسدت القناة"],
      causes: ["السمنة، الإناث، الحمل، الأربعينات (4F)", "نزول وزن سريع", "وراثة", "ارتفاع كوليسترول"],
      treatments: ["تغيير غذاء (تقليل دهون)", "أورسوديزوكسي كوليك أسد (للأحجام الصغيرة)", "استئصال المرارة بالمنظار = العلاج الجذري", "ERCP لاستخراج حصاة من القناة"],
      whatToDo: "ألم >5 ساعات + حمى + يرقان = التهاب مرارة/قنوات → طوارئ." },
    { name: "Gallstones", shortDesc: "Gallbladder stones, severe colic when duct blocked.",
      symptoms: ["Sudden severe RUQ pain (biliary colic)", "Refers to right shoulder/back", "Nausea & vomiting", "Triggered by fatty meal", "Jaundice if duct obstructed"],
      causes: ["4 F's (fat, female, fertile, forty)", "Rapid weight loss", "Genetics", "High cholesterol"],
      treatments: ["Low-fat diet", "Ursodeoxycholic acid (small stones)", "Laparoscopic cholecystectomy = definitive", "ERCP for ductal stones"],
      whatToDo: "Pain >5 h + fever + jaundice = cholecystitis/cholangitis → ER." }),

  d("appendicitis", "emergency", "critical",
    { name: "التهاب الزائدة الدودية", shortDesc: "حالة جراحية طارئة تتطلب استئصال خلال ساعات.",
      symptoms: ["ألم حول السرة ينتقل لأسفل البطن الأيمن خلال 6-12 ساعة", "غثيان وقيء", "فقدان شهية", "حمى خفيفة", "ألم عند الضغط ثم عند رفع اليد (Rebound)"],
      causes: ["انسداد الزائدة بفضلات أو غدد لمفاوية متضخمة", "عدوى"],
      treatments: ["استئصال جراحي (بالمنظار غالباً) خلال 24 ساعة", "مضاد حيوي وريدي قبل وبعد الجراحة"],
      whatToDo: "اشتباه = طوارئ فوراً. لا تأكل، لا تشرب، لا تأخذ مسكن قوي يخفي الأعراض." },
    { name: "Appendicitis", shortDesc: "Surgical emergency requiring removal within hours.",
      symptoms: ["Periumbilical pain migrates to RLQ in 6-12 h", "Nausea, vomiting", "Anorexia", "Low fever", "Tenderness + rebound"],
      causes: ["Luminal obstruction (fecalith, lymphoid hyperplasia)", "Infection"],
      treatments: ["Appendectomy (usually laparoscopic) within 24 h", "Pre/post-op IV antibiotics"],
      whatToDo: "Suspicion = ER NOW. NPO, no strong painkillers that mask the picture." }),
];
