/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceChatRouteImport } from './routes/voice-chat'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'
import { Route as SignLanguageRouteImport } from './routes/sign-language'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as PsychTestsRouteImport } from './routes/psych-tests'
import { Route as PsychChatRouteImport } from './routes/psych-chat'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as MentalHealthRouteImport } from './routes/mental-health'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as FirstAidRouteImport } from './routes/first-aid'
import { Route as EmergencyPlanRouteImport } from './routes/emergency-plan'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiseasesIndexRouteImport } from './routes/diseases.index'
import { Route as ForumIdRouteImport } from './routes/forum.$id'
import { Route as DiseasesIdRouteImport } from './routes/diseases.$id'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as ApiPublicTtsRouteImport } from './routes/api.public.tts'
import { Route as ApiPublicTranslateRouteImport } from './routes/api.public.translate'

const VoiceChatRoute = VoiceChatRouteImport.update({
  id: '/voice-chat',
  path: '/voice-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const SignLanguageRoute = SignLanguageRouteImport.update({
  id: '/sign-language',
  path: '/sign-language',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychTestsRoute = PsychTestsRouteImport.update({
  id: '/psych-tests',
  path: '/psych-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychChatRoute = PsychChatRouteImport.update({
  id: '/psych-chat',
  path: '/psych-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalHealthRoute = MentalHealthRouteImport.update({
  id: '/mental-health',
  path: '/mental-health',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAidRoute = FirstAidRouteImport.update({
  id: '/first-aid',
  path: '/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyPlanRoute = EmergencyPlanRouteImport.update({
  id: '/emergency-plan',
  path: '/emergency-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesIndexRoute = DiseasesIndexRouteImport.update({
  id: '/diseases/',
  path: '/diseases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIdRoute = ForumIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ForumRoute,
} as any)
const DiseasesIdRoute = DiseasesIdRouteImport.update({
  id: '/diseases/$id',
  path: '/diseases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranslateRoute = ApiPublicTranslateRouteImport.update({
  id: '/api/public/translate',
  path: '/api/public/translate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/chat': typeof ChatRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/emergency-plan': typeof EmergencyPlanRoute
  '/first-aid': typeof FirstAidRoute
  '/forum': typeof ForumRouteWithChildren
  '/maps': typeof MapsRoute
  '/medications': typeof MedicationsRoute
  '/mental-health': typeof MentalHealthRoute
  '/parents': typeof ParentsRoute
  '/psych-chat': typeof PsychChatRoute
  '/psych-tests': typeof PsychTestsRoute
  '/reminders': typeof RemindersRoute
  '/research': typeof ResearchRoute
  '/sign-language': typeof SignLanguageRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/therapists': typeof TherapistsRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/diseases/$id': typeof DiseasesIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/diseases/': typeof DiseasesIndexRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/chat': typeof ChatRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/emergency-plan': typeof EmergencyPlanRoute
  '/first-aid': typeof FirstAidRoute
  '/forum': typeof ForumRouteWithChildren
  '/maps': typeof MapsRoute
  '/medications': typeof MedicationsRoute
  '/mental-health': typeof MentalHealthRoute
  '/parents': typeof ParentsRoute
  '/psych-chat': typeof PsychChatRoute
  '/psych-tests': typeof PsychTestsRoute
  '/reminders': typeof RemindersRoute
  '/research': typeof ResearchRoute
  '/sign-language': typeof SignLanguageRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/therapists': typeof TherapistsRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/diseases/$id': typeof DiseasesIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/diseases': typeof DiseasesIndexRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/chat': typeof ChatRoute
  '/doctors': typeof DoctorsRoute
  '/emergency': typeof EmergencyRoute
  '/emergency-plan': typeof EmergencyPlanRoute
  '/first-aid': typeof FirstAidRoute
  '/forum': typeof ForumRouteWithChildren
  '/maps': typeof MapsRoute
  '/medications': typeof MedicationsRoute
  '/mental-health': typeof MentalHealthRoute
  '/parents': typeof ParentsRoute
  '/psych-chat': typeof PsychChatRoute
  '/psych-tests': typeof PsychTestsRoute
  '/reminders': typeof RemindersRoute
  '/research': typeof ResearchRoute
  '/sign-language': typeof SignLanguageRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/therapists': typeof TherapistsRoute
  '/voice-chat': typeof VoiceChatRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/diseases/$id': typeof DiseasesIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/diseases/': typeof DiseasesIndexRoute
  '/api/public/translate': typeof ApiPublicTranslateRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/calculators'
    | '/chat'
    | '/doctors'
    | '/emergency'
    | '/emergency-plan'
    | '/first-aid'
    | '/forum'
    | '/maps'
    | '/medications'
    | '/mental-health'
    | '/parents'
    | '/psych-chat'
    | '/psych-tests'
    | '/reminders'
    | '/research'
    | '/sign-language'
    | '/symptom-checker'
    | '/therapists'
    | '/voice-chat'
    | '/admin/doctors'
    | '/diseases/$id'
    | '/forum/$id'
    | '/diseases/'
    | '/api/public/translate'
    | '/api/public/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/calculators'
    | '/chat'
    | '/doctors'
    | '/emergency'
    | '/emergency-plan'
    | '/first-aid'
    | '/forum'
    | '/maps'
    | '/medications'
    | '/mental-health'
    | '/parents'
    | '/psych-chat'
    | '/psych-tests'
    | '/reminders'
    | '/research'
    | '/sign-language'
    | '/symptom-checker'
    | '/therapists'
    | '/voice-chat'
    | '/admin/doctors'
    | '/diseases/$id'
    | '/forum/$id'
    | '/diseases'
    | '/api/public/translate'
    | '/api/public/tts'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/calculators'
    | '/chat'
    | '/doctors'
    | '/emergency'
    | '/emergency-plan'
    | '/first-aid'
    | '/forum'
    | '/maps'
    | '/medications'
    | '/mental-health'
    | '/parents'
    | '/psych-chat'
    | '/psych-tests'
    | '/reminders'
    | '/research'
    | '/sign-language'
    | '/symptom-checker'
    | '/therapists'
    | '/voice-chat'
    | '/admin/doctors'
    | '/diseases/$id'
    | '/forum/$id'
    | '/diseases/'
    | '/api/public/translate'
    | '/api/public/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  CalculatorsRoute: typeof CalculatorsRoute
  ChatRoute: typeof ChatRoute
  DoctorsRoute: typeof DoctorsRoute
  EmergencyRoute: typeof EmergencyRoute
  EmergencyPlanRoute: typeof EmergencyPlanRoute
  FirstAidRoute: typeof FirstAidRoute
  ForumRoute: typeof ForumRouteWithChildren
  MapsRoute: typeof MapsRoute
  MedicationsRoute: typeof MedicationsRoute
  MentalHealthRoute: typeof MentalHealthRoute
  ParentsRoute: typeof ParentsRoute
  PsychChatRoute: typeof PsychChatRoute
  PsychTestsRoute: typeof PsychTestsRoute
  RemindersRoute: typeof RemindersRoute
  ResearchRoute: typeof ResearchRoute
  SignLanguageRoute: typeof SignLanguageRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
  TherapistsRoute: typeof TherapistsRoute
  VoiceChatRoute: typeof VoiceChatRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  DiseasesIdRoute: typeof DiseasesIdRoute
  DiseasesIndexRoute: typeof DiseasesIndexRoute
  ApiPublicTranslateRoute: typeof ApiPublicTranslateRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-chat': {
      id: '/voice-chat'
      path: '/voice-chat'
      fullPath: '/voice-chat'
      preLoaderRoute: typeof VoiceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-language': {
      id: '/sign-language'
      path: '/sign-language'
      fullPath: '/sign-language'
      preLoaderRoute: typeof SignLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psych-tests': {
      id: '/psych-tests'
      path: '/psych-tests'
      fullPath: '/psych-tests'
      preLoaderRoute: typeof PsychTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psych-chat': {
      id: '/psych-chat'
      path: '/psych-chat'
      fullPath: '/psych-chat'
      preLoaderRoute: typeof PsychChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental-health': {
      id: '/mental-health'
      path: '/mental-health'
      fullPath: '/mental-health'
      preLoaderRoute: typeof MentalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-aid': {
      id: '/first-aid'
      path: '/first-aid'
      fullPath: '/first-aid'
      preLoaderRoute: typeof FirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-plan': {
      id: '/emergency-plan'
      path: '/emergency-plan'
      fullPath: '/emergency-plan'
      preLoaderRoute: typeof EmergencyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/': {
      id: '/diseases/'
      path: '/diseases'
      fullPath: '/diseases/'
      preLoaderRoute: typeof DiseasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$id': {
      id: '/forum/$id'
      path: '/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof ForumIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/diseases/$id': {
      id: '/diseases/$id'
      path: '/diseases/$id'
      fullPath: '/diseases/$id'
      preLoaderRoute: typeof DiseasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/translate': {
      id: '/api/public/translate'
      path: '/api/public/translate'
      fullPath: '/api/public/translate'
      preLoaderRoute: typeof ApiPublicTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ForumRouteChildren {
  ForumIdRoute: typeof ForumIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumIdRoute: ForumIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  CalculatorsRoute: CalculatorsRoute,
  ChatRoute: ChatRoute,
  DoctorsRoute: DoctorsRoute,
  EmergencyRoute: EmergencyRoute,
  EmergencyPlanRoute: EmergencyPlanRoute,
  FirstAidRoute: FirstAidRoute,
  ForumRoute: ForumRouteWithChildren,
  MapsRoute: MapsRoute,
  MedicationsRoute: MedicationsRoute,
  MentalHealthRoute: MentalHealthRoute,
  ParentsRoute: ParentsRoute,
  PsychChatRoute: PsychChatRoute,
  PsychTestsRoute: PsychTestsRoute,
  RemindersRoute: RemindersRoute,
  ResearchRoute: ResearchRoute,
  SignLanguageRoute: SignLanguageRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
  TherapistsRoute: TherapistsRoute,
  VoiceChatRoute: VoiceChatRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  DiseasesIdRoute: DiseasesIdRoute,
  DiseasesIndexRoute: DiseasesIndexRoute,
  ApiPublicTranslateRoute: ApiPublicTranslateRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
