// Common medical sign-language vocabulary (ASL + Arabic Sign Language descriptions)
export interface SignEntry {
  id: string;
  ar: string;
  en: string;
  category: "general" | "symptoms" | "emergency" | "body" | "feelings";
  asl: string; // step-by-step ASL description
  arSign: string; // step-by-step Arabic sign language description
  videoSearch: string; // YouTube search query for instructional video
}

export const SIGN_VOCAB: SignEntry[] = [
  // General medical
  { id: "doctor", ar: "طبيب", en: "Doctor", category: "general",
    asl: "Tap the wrist twice with the 'D' handshape (where a pulse would be checked).",
    arSign: "ضع طرف السبابة على معصم اليد المعاكسة مرتين.",
    videoSearch: "ASL sign doctor" },
  { id: "hospital", ar: "مستشفى", en: "Hospital", category: "general",
    asl: "Draw a cross (+) on the upper arm with the 'H' handshape.",
    arSign: "ارسم علامة + على الذراع بإصبع السبابة.",
    videoSearch: "ASL sign hospital" },
  { id: "medicine", ar: "دواء", en: "Medicine", category: "general",
    asl: "Place middle finger of dominant hand into palm of non-dominant, twist back and forth.",
    arSign: "افتح كف اليد وحرك إصبع الإبهام دائريًا فوقه.",
    videoSearch: "ASL sign medicine" },
  { id: "nurse", ar: "ممرّض/ة", en: "Nurse", category: "general",
    asl: "Tap the inside of wrist twice with 'N' handshape.",
    arSign: "ضع إصبعين على المعصم برفق مرتين.",
    videoSearch: "ASL sign nurse" },
  { id: "appointment", ar: "موعد", en: "Appointment", category: "general",
    asl: "'A' handshape moves in circle then taps down on back of other hand.",
    arSign: "أشر إلى المعصم كأنك تشير لساعة ثم انقر برفق.",
    videoSearch: "ASL sign appointment" },
  { id: "allergy", ar: "حساسية", en: "Allergy", category: "general",
    asl: "Index finger touches nose, then both index fingers move apart.",
    arSign: "المس الأنف ثم حرّك السبابتين بعيدًا عن بعضهما.",
    videoSearch: "ASL sign allergy" },
  { id: "surgery", ar: "جراحة/عملية", en: "Surgery", category: "general",
    asl: "'A' thumb traces a line across the palm (like a scalpel).",
    arSign: "حرّك الإبهام عبر راحة اليد كالمشرط.",
    videoSearch: "ASL sign surgery" },
  { id: "blood", ar: "دم", en: "Blood", category: "body",
    asl: "Sign 'red' on the lips, then move open hand downward off the back of other hand.",
    arSign: "المس الشفة ثم حرّك اليد للأسفل لتمثيل تدفق الدم.",
    videoSearch: "ASL sign blood" },

  // Symptoms
  { id: "pain", ar: "ألم", en: "Pain / Hurt", category: "symptoms",
    asl: "Both index fingers point at each other, twist in opposite directions near the area that hurts.",
    arSign: "حرّك السبابتين تجاه بعضهما بحركة دائرية معكوسة قرب موقع الألم.",
    videoSearch: "ASL sign pain hurt" },
  { id: "fever", ar: "حمى/سخونية", en: "Fever", category: "symptoms",
    asl: "Back of hand or 'F' handshape touches forehead.",
    arSign: "المس الجبهة بظهر اليد للإشارة لارتفاع الحرارة.",
    videoSearch: "ASL sign fever" },
  { id: "headache", ar: "صداع", en: "Headache", category: "symptoms",
    asl: "Two index fingers point at temple/forehead and twist.",
    arSign: "ضع السبابتين على الجبهة وحرّكهما دائريًا.",
    videoSearch: "ASL sign headache" },
  { id: "stomachache", ar: "ألم بطن", en: "Stomach ache", category: "symptoms",
    asl: "Both bent hands touch stomach, twist in opposite directions.",
    arSign: "المس البطن بكلتا اليدين بحركة دائرية متضادة.",
    videoSearch: "ASL sign stomach ache" },
  { id: "nausea", ar: "غثيان", en: "Nausea / Vomiting", category: "symptoms",
    asl: "Open hand circles over stomach.",
    arSign: "حرّك راحة اليد دائريًا فوق المعدة.",
    videoSearch: "ASL sign nausea vomit" },
  { id: "cough", ar: "كحة/سعال", en: "Cough", category: "symptoms",
    asl: "Bent fingers tap chest twice.",
    arSign: "اطرق الصدر بأطراف الأصابع مرتين.",
    videoSearch: "ASL sign cough" },
  { id: "dizzy", ar: "دوخة", en: "Dizzy", category: "symptoms",
    asl: "Claw-shaped hand circles in front of face.",
    arSign: "حرّك اليد دائريًا أمام الوجه بأصابع منحنية.",
    videoSearch: "ASL sign dizzy" },
  { id: "tired", ar: "تعبان", en: "Tired", category: "feelings",
    asl: "Both bent hands on chest, drop slightly.",
    arSign: "ضع راحتي اليدين على الصدر مع تنهيدة وحركة هبوط.",
    videoSearch: "ASL sign tired" },
  { id: "breathing", ar: "صعوبة تنفس", en: "Difficulty breathing", category: "symptoms",
    asl: "Both flat hands move in/out from chest with strain.",
    arSign: "حرّك راحتي اليدين قرب الصدر بحركة شهيق وزفير متعبة.",
    videoSearch: "ASL sign trouble breathing" },

  // Emergency
  { id: "emergency", ar: "طوارئ", en: "Emergency", category: "emergency",
    asl: "'E' handshape shakes/trembles in front of you.",
    arSign: "حرّك يديك بسرعة أمامك للإشارة للاستعجال.",
    videoSearch: "ASL sign emergency" },
  { id: "help", ar: "مساعدة", en: "Help", category: "emergency",
    asl: "Closed fist (thumb up) sits on flat palm; both lift together.",
    arSign: "ضع قبضة على راحة اليد المعاكسة وارفعهما معًا.",
    videoSearch: "ASL sign help" },
  { id: "call_911", ar: "اتصل بالإسعاف", en: "Call ambulance", category: "emergency",
    asl: "Sign 'phone' (Y handshape near ear), then sign '911' or 'ambulance' (siren rotation on top of head).",
    arSign: "أشر للأذن بإصبعين كالهاتف ثم ارسم دائرة فوق الرأس كصافرة الإسعاف.",
    videoSearch: "ASL sign call 911 ambulance" },
  { id: "stop", ar: "توقف", en: "Stop", category: "emergency",
    asl: "Edge of dominant flat hand chops down onto palm of non-dominant.",
    arSign: "اضرب جانب اليد على راحة اليد الأخرى بحدة.",
    videoSearch: "ASL sign stop" },
  { id: "danger", ar: "خطر", en: "Danger", category: "emergency",
    asl: "'A' thumb taps the back of the other fist twice forcefully.",
    arSign: "اضرب قبضة على ظهر القبضة الأخرى بقوة مرتين.",
    videoSearch: "ASL sign danger" },

  // Body parts
  { id: "head", ar: "رأس", en: "Head", category: "body",
    asl: "Bent hand touches side of head twice (temple to jaw).",
    arSign: "المس جانب الرأس مرتين من الصدغ للذقن.",
    videoSearch: "ASL sign head" },
  { id: "heart", ar: "قلب", en: "Heart", category: "body",
    asl: "Middle finger of each hand taps chest over the heart.",
    arSign: "ضع راحة اليد على الصدر فوق القلب.",
    videoSearch: "ASL sign heart" },
  { id: "stomach", ar: "معدة", en: "Stomach", category: "body",
    asl: "Bent hand pats the stomach twice.",
    arSign: "اطرق على المعدة بكف اليد مرتين.",
    videoSearch: "ASL sign stomach" },
  { id: "back", ar: "ظهر", en: "Back", category: "body",
    asl: "Tap the back of your shoulder with flat hand.",
    arSign: "أشر إلى ظهرك بطرف اليد.",
    videoSearch: "ASL sign back body" },

  // Feelings
  { id: "scared", ar: "خايف", en: "Scared / Afraid", category: "feelings",
    asl: "Both 'S' fists open suddenly toward chest.",
    arSign: "افتح القبضتين بسرعة أمام الصدر مع تعبير خوف.",
    videoSearch: "ASL sign scared afraid" },
  { id: "sad", ar: "حزين", en: "Sad", category: "feelings",
    asl: "Both open hands slowly slide down the face.",
    arSign: "حرّك راحتي اليدين على الوجه إلى الأسفل ببطء.",
    videoSearch: "ASL sign sad" },
  { id: "happy", ar: "سعيد", en: "Happy", category: "feelings",
    asl: "Both flat hands brush up the chest with circular motion.",
    arSign: "حرّك راحتي اليدين على الصدر بحركة دائرية لأعلى.",
    videoSearch: "ASL sign happy" },
  { id: "anxious", ar: "قلقان", en: "Anxious / Worried", category: "feelings",
    asl: "Both bent hands move in alternating circles in front of chest.",
    arSign: "حرّك يديك بشكل دائري متبادل أمام الصدر.",
    videoSearch: "ASL sign anxious worried" },
  { id: "ok", ar: "تمام/كويس", en: "OK / I'm fine", category: "general",
    asl: "Make 'OK' with thumb-index circle, other fingers extended.",
    arSign: "ضع طرف الإبهام والسبابة معًا في دائرة مع رفع باقي الأصابع.",
    videoSearch: "ASL sign okay fine" },
  { id: "yes", ar: "نعم", en: "Yes", category: "general",
    asl: "Closed fist nods up and down (like a head nodding yes).",
    arSign: "حرّك قبضة اليد لأعلى ولأسفل مثل إيماءة الرأس.",
    videoSearch: "ASL sign yes" },
  { id: "no", ar: "لا", en: "No", category: "general",
    asl: "Index + middle fingers tap thumb (like a mouth saying no).",
    arSign: "اطرق السبابة والوسطى على الإبهام كالفم يقول لا.",
    videoSearch: "ASL sign no" },
];
